package org.egov.excelingestion.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.egov.excelingestion.config.ErrorConstants;
import org.egov.excelingestion.config.ExcelIngestionConfig;
import org.egov.excelingestion.config.ProcessingConstants;
import org.egov.excelingestion.constants.GenerationConstants;
import org.egov.excelingestion.exception.CustomExceptionHandler;
import org.egov.excelingestion.repository.GeneratedFileRepository;
import org.egov.excelingestion.util.CellProtectionManager;
import org.egov.excelingestion.util.ColumnDefMaker;
import org.egov.excelingestion.util.ExcelDataPopulator;
import org.egov.excelingestion.util.ExcelStyleHelper;
import org.egov.excelingestion.util.ExcelUtil;
import org.egov.excelingestion.util.SchemaColumnDefUtil;
import org.egov.excelingestion.util.SignatureUtil;
import org.egov.excelingestion.web.models.GenerateResource;
import org.egov.excelingestion.web.models.ProcessResource;
import org.egov.excelingestion.web.models.excel.ColumnDef;
import org.egov.tracer.model.CustomException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Tests for {@link ImmutableJoinService} - the server-authoritative join that reconstructs pre-filled
 * immutable cells from the original generated baseline (unprotected join mode).
 *
 * <p>Two nested suites:
 * <ul>
 *   <li>{@link Unit} - ExcelUtil is mocked so {@code convertSheetToMapListCached} returns controlled
 *       in-memory row maps; the test inspects those maps after the join to assert what was restored vs
 *       kept. Fast, focused on the join logic and fail-closed paths.</li>
 *   <li>{@link EndToEnd} - exercises the REAL components (no mocking of the populator/parser/join): a
 *       workbook is GENERATED by the real {@link ExcelDataPopulator}, edited as a user would, then run
 *       through the real {@link ImmutableJoinService}. Only the filestore + repository are mocked.</li>
 * </ul>
 */
class ImmutableJoinServiceTest {

    // ============================================================================================
    // Mocked unit tests: controlled in-memory row maps; asserts what the join restores vs keeps.
    // ExcelUtil's STATIC helpers (getValueAsString / getCellValueAsString) run for real.
    // ============================================================================================
    @Nested
    @ExtendWith(MockitoExtension.class)
    class Unit {

        @Mock private GeneratedFileRepository generatedFileRepository;
        @Mock private FileStoreService fileStoreService;
        @Mock private ExcelUtil excelUtil;
        @Mock private SchemaColumnDefUtil schemaColumnDefUtil;
        @Mock private ExcelIngestionConfig config;

        private ImmutableJoinService service;

        private static final String TENANT = "mz";
        private static final String TYPE = "unified-console-validation"; // a join-mode family (also: attendanceRegister/attendanceRegisterAttendee)
        private static final String REF = "campaign-1";
        private static final String GEN_ID = "gen-1";
        private static final String TEST_SECRET = "unit-test-signing-secret";
        private static final String UPLOAD_FS = "upload-fs";
        private static final String BASELINE_FS = "baseline-fs";
        private static final String SHEET = "Users";
        private static final String ROW_ID = ProcessingConstants.ROW_ID_COLUMN_NAME;
        private static final String ROW_NUM = ProcessingConstants.ACTUAL_ROW_NUMBER_KEY;

        private Workbook uploadedWorkbook;
        private Workbook baselineWorkbook;
        private ProcessResource resource;
        private Map<String, Map<String, Object>> sheetNameToSchema;

        @BeforeEach
        void setUp() throws Exception {
            service = new ImmutableJoinService(generatedFileRepository, fileStoreService, excelUtil,
                    schemaColumnDefUtil, new ObjectMapper(), new CustomExceptionHandler(), config);

            uploadedWorkbook = new XSSFWorkbook();
            uploadedWorkbook.createSheet(SHEET);
            Row metaRow = uploadedWorkbook.createSheet(GenerationConstants.META_SHEET_NAME).createRow(0);
            metaRow.createCell(GenerationConstants.META_GENERATION_ID_CELL).setCellValue(GEN_ID);
            metaRow.createCell(GenerationConstants.META_SIGNATURE_CELL).setCellValue(SignatureUtil.sign(GEN_ID, TEST_SECRET));

            baselineWorkbook = new XSSFWorkbook();
            baselineWorkbook.createSheet(SHEET);

            resource = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).build();

            sheetNameToSchema = new HashMap<>();
            sheetNameToSchema.put(SHEET, new HashMap<>());

            lenient().when(config.isImmutableEnforce()).thenReturn(true);
            lenient().when(config.isImmutableSignatureEnforce()).thenReturn(true);
            lenient().when(config.getImmutableSigningSecret()).thenReturn(TEST_SECRET);
            lenient().when(generatedFileRepository.findByGenerationId(GEN_ID, TENANT)).thenReturn(
                    GenerateResource.builder().id(GEN_ID).fileStoreId(BASELINE_FS)
                            .referenceId(REF).type(TYPE).tenantId(TENANT).build());
            lenient().when(fileStoreService.downloadExcelFromFileStore(BASELINE_FS, TENANT)).thenReturn(baselineWorkbook);
            lenient().when(schemaColumnDefUtil.convertSchemaToColumnDefs(anyString())).thenReturn(columnDefs());
        }

        // immutable: name (freezeColumn), village (freezeTillData), roles (freezeColumn = multi-select parent)
        // conditional: phone (freezeColumnIfFilled); editable: comment (no flag)
        private List<ColumnDef> columnDefs() {
            return Arrays.asList(
                    ColumnDef.builder().name("name").freezeColumn(true).build(),
                    ColumnDef.builder().name("village").freezeTillData(true).build(),
                    ColumnDef.builder().name("roles").freezeColumn(true).build(),
                    ColumnDef.builder().name("phone").freezeColumnIfFilled(true).build(),
                    ColumnDef.builder().name("comment").build());
        }

        private Map<String, Object> row(Object... kv) {
            Map<String, Object> m = new HashMap<>();
            for (int i = 0; i < kv.length; i += 2) {
                m.put((String) kv[i], kv[i + 1]);
            }
            return m;
        }

        private void stubRows(List<Map<String, Object>> uploaded, List<Map<String, Object>> baseline) {
            when(excelUtil.convertSheetToMapListCached(eq(UPLOAD_FS), eq(SHEET), any())).thenReturn(uploaded);
            when(excelUtil.convertSheetToMapListCached(eq(BASELINE_FS), eq(SHEET), any())).thenReturn(baseline);
        }

        private void run() {
            service.applyImmutableBaseline(uploadedWorkbook, resource, sheetNameToSchema);
        }

        @Test
        void restoresImmutable_keepsEditable_andMultiSelectChildren() {
            Map<String, Object> up = row(ROW_ID, "r1",
                    "name", "HACKED", "village", "HACKED_V", "phone", "999",
                    "comment", "user note", "roles_MULTISELECT_1", "HACKED_ROLE", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1",
                    "name", "Real Name", "village", "V1", "phone", "111",
                    "comment", "orig", "roles_MULTISELECT_1", "ADMIN", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            run();

            assertEquals("Real Name", up.get("name"), "freezeColumn restored from baseline");
            assertEquals("V1", up.get("village"), "freezeTillData restored from baseline");
            assertEquals("111", up.get("phone"), "freezeColumnIfFilled (baseline filled) restored");
            assertEquals("ADMIN", up.get("roles_MULTISELECT_1"), "multi-select child restored from baseline");
            assertEquals("user note", up.get("comment"), "editable column kept from file");
            assertEquals(3, up.get(ROW_NUM), "uploaded row number is preserved");
        }

        @Test
        void skipSet_excludesImmutableColumnAbsentFromBaseline() {
            // 'village' is freezeTillData (immutable) in the CURRENT schema, but this baseline row predates it
            // (no 'village' key). The join cannot reconstruct it, so it must NOT appear in the returned skip
            // set - otherwise the user's value would bypass validation. 'name' IS present and reconstructed.
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED", "village", "USER_TYPED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name"); // no 'village' key
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            Map<String, Set<String>> skip = service.applyImmutableBaseline(uploadedWorkbook, resource, sheetNameToSchema);

            assertEquals("Real Name", up.get("name"), "present immutable column restored from baseline");
            assertEquals("USER_TYPED", up.get("village"), "immutable column absent from baseline is NOT overwritten");
            Set<String> sheetSkip = skip.getOrDefault(SHEET, Collections.emptySet());
            assertTrue(sheetSkip.contains("name"), "actually-reconstructed column is in the skip set");
            assertFalse(sheetSkip.contains("village"), "column absent from baseline must NOT be in the skip set");
        }

        @Test
        void boundaryColumn_prefilled_lockedEvenThoughNotInSchema() {
            // Boundary/hierarchy columns ("HZ_COUNTRY" etc.) are dynamic - NOT in the schema columnDefs.
            // A prefilled boundary cell must be locked to baseline (freezeColumnIfFilled); an empty boundary
            // level must stay user-editable.
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok",
                    "HZ_COUNTRY", "HACKED_COUNTRY", "HZ_PROVINCE", "UserPicked");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok",
                    "HZ_COUNTRY", "Mozambique", "HZ_PROVINCE", null);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema);

            assertEquals("Mozambique", up.get("HZ_COUNTRY"), "prefilled boundary column locked to baseline value");
            assertEquals("UserPicked", up.get("HZ_PROVINCE"), "empty-baseline boundary level stays user-editable");
        }

        @Test
        void boundarySheet_noSchemaImmutableColumns_stillLocksBoundaryAndCode() {
            // Regression for the Boundary List leak: that sheet's MDMS schema has ONLY editable target
            // columns, so the derived immutable set is EMPTY. joinSheet used to return at `immutable.isEmpty()`
            // BEFORE the dynamic boundary-column locking ran, leaving prefilled boundary selections + the
            // derived code unprotected - a user could tamper them and the change would persist. The boundary
            // columns + code must still be reconstructed from the baseline on an all-editable-schema sheet;
            // only the genuine target column stays user-controlled.
            when(schemaColumnDefUtil.convertSchemaToColumnDefs(anyString()))
                    .thenReturn(List.of(ColumnDef.builder().name("target").build())); // no freeze flag -> immutable empty
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "target", "55",
                    "HZ_COUNTRY", "HACKED", "HZ_PROVINCE", "HACKEDPROV",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "FAKE_CODE");
            Map<String, Object> base = row(ROW_ID, "r1", "target", "10",
                    "HZ_COUNTRY", "Manland", "HZ_PROVINCE", "RealProv",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "ZQ_VILL_231");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema);

            assertEquals("Manland", up.get("HZ_COUNTRY"),
                    "boundary column reconstructed even when the schema has NO immutable columns");
            assertEquals("RealProv", up.get("HZ_PROVINCE"), "prefilled boundary level locked to baseline");
            assertEquals("ZQ_VILL_231", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived boundary code restored to baseline (tamper corrected) on a no-immutable-schema sheet");
            assertEquals("55", up.get("target"), "editable target column stays user-controlled");
        }

        @Test
        void boundaryCode_restoredWhenLockedSelectionTampered() {
            // Boundary fully prefilled (COUNTRY+PROVINCE) -> locked. User tampered them + the derived code.
            // Path is unchanged after restore (no deeper level added) -> the baseline code is authoritative.
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "HACK", "HZ_PROVINCE", "HACKPROV",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "WRONG_CODE");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema);

            assertEquals("Maryland", up.get("HZ_PROVINCE"), "locked boundary level restored");
            assertEquals("HZ_MZ_MARYLAND", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived boundary code restored to baseline when path unchanged (tamper corrected)");
        }

        @Test
        void boundaryCode_keptWhenUserDeepensBoundary() {
            // Baseline has only COUNTRY; PROVINCE empty -> user legitimately deepens (picks Maryland). The
            // derived code must reflect the user's deeper selection, NOT be reset to the baseline country code.
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_PROVINCE", null,
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema);

            assertEquals("Maryland", up.get("HZ_PROVINCE"), "user-deepened (empty-baseline) level kept");
            assertEquals("HZ_MZ_MARYLAND", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived code kept for the user's deeper selection, not reset to baseline country code");
        }

        @Test
        void freezeColumnIfFilled_emptyBaseline_keepsUserInput() {
            Map<String, Object> up = row(ROW_ID, "r1", "name", "X", "phone", "user-typed");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "X", "phone", null); // empty -> editable
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            run();

            assertEquals("user-typed", up.get("phone"), "empty-baseline freezeColumnIfFilled cell stays editable");
        }

        @Test
        void newRow_withoutRowId_isTrustedVerbatim() {
            Map<String, Object> existing = row(ROW_ID, "r1", "name", "hack");
            Map<String, Object> newRow = row("name", "Brand New", "comment", "x"); // no row-id
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real");
            stubRows(new ArrayList<>(List.of(existing, newRow)), new ArrayList<>(List.of(base)));

            run();

            assertEquals("Real", existing.get("name"), "existing row immutable restored");
            assertEquals("Brand New", newRow.get("name"), "new row (no id) trusted verbatim");
        }

        @Test
        void unknownRowId_failsClosed() {
            stubRows(new ArrayList<>(List.of(row(ROW_ID, "ghost", "name", "x"))),
                    new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "Real"))));
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void duplicateRowId_failsClosed() {
            stubRows(new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "a"), row(ROW_ID, "r1", "name", "b"))),
                    new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "Real"))));
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void deletedRow_orphan_failsClosed() {
            // baseline has r1 + r2; upload has only r1 -> r2 is an orphan (deleted pre-filled row)
            stubRows(new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "a"))),
                    new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "A"), row(ROW_ID, "r2", "name", "B"))));
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void identityMismatch_failsClosed() throws Exception {
            when(generatedFileRepository.findByGenerationId(GEN_ID, TENANT)).thenReturn(
                    GenerateResource.builder().id(GEN_ID).fileStoreId(BASELINE_FS)
                            .referenceId("OTHER-CAMPAIGN").type(TYPE).tenantId(TENANT).build());
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void baselineNotFound_failsClosed() throws Exception {
            when(generatedFileRepository.findByGenerationId(GEN_ID, TENANT)).thenReturn(null);
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void missingGenerationId_withRowIdColumn_failsClosed() {
            // Metadata sheet stripped, but the hidden row-id column remains -> tampering -> fail closed.
            removeMetaSheet();
            uploadedWorkbook.getSheet(SHEET).createRow(0).createCell(0)
                    .setCellValue(ProcessingConstants.ROW_ID_COLUMN_NAME);
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void missingGenerationId_noRowIdColumn_failsClosed() {
            // A join-mode upload MUST carry an embedded generationId (the generated template always has one).
            // A file lacking both the meta sheet and the row-id column is not the generated template for this
            // campaign -> fail closed. (Previously this was silently skipped as "legacy", which let arbitrary
            // non-generated files bypass immutability - now removed.)
            removeMetaSheet();
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void outOfScopeType_skipsJoinEntirely() {
            // A type outside the join-mode families must be left completely untouched (no baseline lookup, no join).
            ProcessResource other = ProcessResource.builder()
                    .tenantId(TENANT).type("someUnrelatedType-validation").referenceId(REF).fileStoreId(UPLOAD_FS).build();
            assertDoesNotThrow(() -> service.applyImmutableBaseline(uploadedWorkbook, other, sheetNameToSchema));
            verifyNoInteractions(generatedFileRepository, fileStoreService);
        }

        @Test
        void attendanceRegisterType_isInScope_andJoins() {
            // attendanceRegister is a join-mode family -> immutable cells are reconstructed from the baseline.
            ProcessResource attendance = ProcessResource.builder()
                    .tenantId(TENANT).type("attendanceRegister-validation").referenceId(REF).fileStoreId(UPLOAD_FS).build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, attendance, sheetNameToSchema);

            assertEquals("Real Name", up.get("name"), "attendanceRegister type is in join scope -> immutable restored");
        }

        @Test
        void attendanceRegisterAttendeeType_isInScope_andJoins() {
            // attendanceRegisterAttendee is covered by the "attendanceRegister" prefix -> also in scope.
            ProcessResource attendee = ProcessResource.builder()
                    .tenantId(TENANT).type("attendanceRegisterAttendee-validation").referenceId(REF).fileStoreId(UPLOAD_FS).build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, attendee, sheetNameToSchema);

            assertEquals("Real Name", up.get("name"), "attendanceRegisterAttendee type is in join scope -> immutable restored");
        }

        @Test
        void killSwitchOff_skipsEntirely() {
            when(config.isImmutableEnforce()).thenReturn(false);
            assertDoesNotThrow(this::run);
            verifyNoInteractions(generatedFileRepository, fileStoreService);
        }

        @Test
        void tamperedSignature_failsClosed() {
            // Genuine generationId + correct campaign, but the authenticity signature is wrong -> this is not
            // the exact downloaded file (e.g. a hand-built look-alike stamped with a leaked generationId).
            setMetaSignature("not-the-real-signature");
            CustomException ex = assertThrows(CustomException.class, this::run);
            assertEquals(ErrorConstants.IMMUTABLE_SIGNATURE_INVALID, ex.getCode());
        }

        @Test
        void missingSignature_failsClosed() {
            // generationId present, but no signature -> not the genuine downloaded file -> reject.
            setMetaSignature("");
            CustomException ex = assertThrows(CustomException.class, this::run);
            assertEquals(ErrorConstants.IMMUTABLE_SIGNATURE_INVALID, ex.getCode());
        }

        @Test
        void signatureEnforceDisabled_skipsSignatureCheck() {
            when(config.isImmutableSignatureEnforce()).thenReturn(false);
            setMetaSignature("garbage");   // bad signature is ignored when enforcement is off
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, resource, sheetNameToSchema);

            assertEquals("Real Name", up.get("name"), "join still runs when signature enforcement is disabled");
        }

        private void setMetaSignature(String value) {
            Row r = uploadedWorkbook.getSheet(GenerationConstants.META_SHEET_NAME).getRow(0);
            Cell c = r.getCell(GenerationConstants.META_SIGNATURE_CELL);
            if (c == null) c = r.createCell(GenerationConstants.META_SIGNATURE_CELL);
            c.setCellValue(value);
        }

        private void removeMetaSheet() {
            uploadedWorkbook.removeSheetAt(uploadedWorkbook.getSheetIndex(GenerationConstants.META_SHEET_NAME));
        }
    }

    // ============================================================================================
    // End-to-end integration: real ExcelDataPopulator generation -> user edits -> real join.
    // Only the filestore + repository boundaries are mocked. A memoizing spy on ExcelUtil reproduces
    // the production @Cacheable behaviour so the in-place mutation the join performs is observable.
    // ============================================================================================
    @Nested
    class EndToEnd {

        private static final String TENANT = "mz";
        private static final String TYPE = "unified-console-validation"; // a join-mode family (also: attendanceRegister/attendanceRegisterAttendee)
        private static final String REF = "campaign-1";
        private static final String GEN_ID = "gen-e2e-1";
        private static final String TEST_SECRET = "e2e-test-signing-secret";
        private static final String UPLOAD_FS = "upload-fs";
        private static final String BASELINE_FS = "baseline-fs";
        private static final String SHEET = "Users";
        private static final String USAGE = ProcessingConstants.USER_USAGE_COLUMN_KEY;

        private ExcelIngestionConfig config;
        private ExcelDataPopulator populator;
        private SchemaColumnDefUtil schemaColumnDefUtil;
        private ExcelUtil excelUtil;                 // memoizing spy
        private GeneratedFileRepository repo;
        private FileStoreService fileStore;
        private ImmutableJoinService join;

        private final Map<String, List<Map<String, Object>>> parseCache = new HashMap<>();

        @BeforeEach
        void setUp() {
            config = new ExcelIngestionConfig();
            config.setImmutableEnforce(true);
            config.setImmutableSignatureEnforce(true);          // exercise the exact-file signature gate end-to-end
            config.setImmutableSigningSecret(TEST_SECRET);
            config.setExcelSheetPassword("testpwd");   // a password IS configured; join mode must still skip protection
            config.setExcelRowLimit(100);
            config.setExcelSheetZoom(60);
            config.setValidationErrorColor("#ff0000");
            config.setServerTimezone("UTC");

            ExcelStyleHelper styleHelper = new ExcelStyleHelper();
            CellProtectionManager cpm = new CellProtectionManager(config, styleHelper);
            populator = new ExcelDataPopulator(config, styleHelper, cpm);

            CustomExceptionHandler exceptionHandler = new CustomExceptionHandler();
            schemaColumnDefUtil = new SchemaColumnDefUtil(new ColumnDefMaker(), exceptionHandler);

            excelUtil = spy(new ExcelUtil());
            // Reproduce @Cacheable: same (fileStoreId, sheetName) -> same list instance, so the join's
            // in-place mutation is visible when we re-fetch.
            doAnswer(inv -> {
                String key = inv.getArgument(0) + "|" + inv.getArgument(1);
                return parseCache.computeIfAbsent(key, k -> {
                    try {
                        @SuppressWarnings("unchecked")
                        List<Map<String, Object>> parsed = (List<Map<String, Object>>) inv.callRealMethod();
                        return parsed;
                    } catch (Throwable t) {
                        throw new RuntimeException(t);
                    }
                });
            }).when(excelUtil).convertSheetToMapListCached(anyString(), anyString(), any());

            repo = mock(GeneratedFileRepository.class);
            fileStore = mock(FileStoreService.class);
            join = new ImmutableJoinService(repo, fileStore, excelUtil, schemaColumnDefUtil,
                    new ObjectMapper(), exceptionHandler, config);
        }

        // Schema: name (freezeColumn), village (freezeTillData), phone (freezeColumnIfFilled),
        // comment (editable), HCM_ADMIN_CONSOLE_USER_USAGE (freezeColumn in schema, but join-EXCLUDED -> editable).
        private String schemaJson() {
            return "{\"stringProperties\":["
                    + "{\"name\":\"name\",\"orderNumber\":1,\"freezeColumn\":true},"
                    + "{\"name\":\"village\",\"orderNumber\":2,\"freezeTillData\":true},"
                    + "{\"name\":\"phone\",\"orderNumber\":3,\"freezeColumnIfFilled\":true},"
                    + "{\"name\":\"comment\",\"orderNumber\":4},"
                    + "{\"name\":\"" + USAGE + "\",\"orderNumber\":5,\"freezeColumn\":true}"
                    + "]}";
        }

        private Map<String, Object> rowOf(String name, String village, String phone, String comment, String usage) {
            Map<String, Object> m = new HashMap<>();
            m.put("name", name);
            m.put("village", village);
            if (phone != null) m.put("phone", phone);
            m.put("comment", comment);
            m.put(USAGE, usage);
            return m;
        }

        private byte[] toBytes(Workbook wb) throws Exception {
            try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
                wb.write(bos);
                return bos.toByteArray();
            }
        }

        private Workbook fromBytes(byte[] bytes) throws Exception {
            return new XSSFWorkbook(new ByteArrayInputStream(bytes));
        }

        private int colIndex(Sheet sheet, String header) {
            Row r0 = sheet.getRow(0);
            for (int c = 0; c < r0.getLastCellNum(); c++) {
                Cell cell = r0.getCell(c);
                if (cell != null && header.equals(cell.getStringCellValue())) return c;
            }
            return -1;
        }

        private void setCell(Sheet sheet, int sheetRow, int col, String value) {
            Row r = sheet.getRow(sheetRow);
            if (r == null) r = sheet.createRow(sheetRow);
            Cell c = r.getCell(col);
            if (c == null) c = r.createCell(col);
            c.setCellValue(value);
        }

        /** Generates a join-mode baseline workbook with {@code n} pre-filled rows (phone empty on row index 1). */
        private byte[] generateBaseline(int n) throws Exception {
            List<ColumnDef> columns = schemaColumnDefUtil.convertSchemaToColumnDefs(schemaJson());
            List<Map<String, Object>> data = new ArrayList<>(n);
            for (int i = 0; i < n; i++) {
                String phone = (i == 1) ? null : ("100" + i);       // row index 1 has empty phone
                data.add(rowOf("Name" + i, "V" + i, phone, "c" + i, "Active"));
            }
            // 6-arg with joinMode=true: generation join-mode is opt-in (the 5-arg defaults to protected).
            Workbook wb = populator.populateSheetWithData(new XSSFWorkbook(), SHEET, columns, data, new HashMap<>(), true);
            // Mirror ConfigBasedGenerationService: embed the generationId + authenticity signature in the meta sheet.
            Row metaRow = wb.createSheet(GenerationConstants.META_SHEET_NAME).createRow(0);
            metaRow.createCell(GenerationConstants.META_GENERATION_ID_CELL).setCellValue(GEN_ID);
            metaRow.createCell(GenerationConstants.META_SIGNATURE_CELL).setCellValue(SignatureUtil.sign(GEN_ID, TEST_SECRET));
            return toBytes(wb);
        }

        private void wireMocks(byte[] baselineBytes) throws Exception {
            when(repo.findByGenerationId(GEN_ID, TENANT)).thenReturn(GenerateResource.builder()
                    .id(GEN_ID).fileStoreId(BASELINE_FS).referenceId(REF).type(TYPE).tenantId(TENANT).build());
            when(fileStore.downloadExcelFromFileStore(BASELINE_FS, TENANT)).thenReturn(fromBytes(baselineBytes));
        }

        private Map<String, Map<String, Object>> sheetSchemaMap() throws Exception {
            Map<String, Map<String, Object>> m = new HashMap<>();
            m.put(SHEET, new ObjectMapper().readValue(schemaJson(), Map.class));
            return m;
        }

        private ProcessResource resource() {
            return ProcessResource.builder().tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).build();
        }

        @Test
        void generatedTemplate_isUnprotected_andHasHiddenRowIdColumn() throws Exception {
            byte[] bytes = generateBaseline(3);
            Workbook wb = fromBytes(bytes);
            Sheet sheet = wb.getSheet(SHEET);

            // R1: copy-paste works -> the sheet must NOT be protected, even though a password is configured.
            assertFalse(sheet.getProtect(), "Join-mode generated sheet must be unprotected");

            int idCol = colIndex(sheet, ProcessingConstants.ROW_ID_COLUMN_NAME);
            assertTrue(idCol >= 0, "Hidden row-id column must be stamped");
            assertTrue(sheet.isColumnHidden(idCol), "Row-id column must be hidden");
            assertFalse(sheet.getRow(2).getCell(idCol).getStringCellValue().isEmpty(), "Each pre-filled row gets a row-id");
            assertNotNull(wb.getSheet(GenerationConstants.META_SHEET_NAME), "generationId meta sheet present");
            wb.close();
        }

        @Test
        void endToEnd_restoresTamperedImmutable_keepsEditable_allowsNewRow() throws Exception {
            byte[] baselineBytes = generateBaseline(3);
            wireMocks(baselineBytes);

            Workbook uploaded = fromBytes(baselineBytes);
            Sheet up = uploaded.getSheet(SHEET);
            int cName = colIndex(up, "name");
            int cVillage = colIndex(up, "village");
            int cPhone = colIndex(up, "phone");
            int cComment = colIndex(up, "comment");
            int cUsage = colIndex(up, USAGE);

            // --- user/attacker edits on the unprotected sheet ---
            setCell(up, 2, cName, "HACKED");        // row0 immutable freezeColumn  -> must be restored
            setCell(up, 2, cUsage, "Inactive");     // row0 active/inactive          -> editable, must be KEPT
            setCell(up, 3, cPhone, "999");          // row1 phone (baseline empty)   -> editable, must be KEPT
            setCell(up, 4, cVillage, "HACKED_V");   // row2 freezeTillData           -> must be restored
            // new row at sheet row 5 (no row-id) -> trusted as new
            setCell(up, 5, cName, "NewGuy");
            setCell(up, 5, cComment, "brand new");

            join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap());

            List<Map<String, Object>> rows = excelUtil.convertSheetToMapListCached(UPLOAD_FS, SHEET, up);
            assertEquals(4, rows.size(), "3 existing + 1 new row");

            assertEquals("Name0", rows.get(0).get("name"), "freezeColumn tamper restored from baseline");
            assertEquals("Inactive", rows.get(0).get(USAGE), "active/inactive column kept (excluded from join)");
            assertEquals("999", rows.get(1).get("phone"), "freezeColumnIfFilled with empty baseline -> user value kept");
            assertEquals("V2", rows.get(2).get("village"), "freezeTillData tamper restored from baseline");
            assertEquals("NewGuy", rows.get(3).get("name"), "new row trusted verbatim");
            assertNull(rows.get(3).get(ProcessingConstants.ROW_ID_COLUMN_NAME), "new row has no row-id");

            uploaded.close();
        }

        @Test
        void endToEnd_deletedPreFilledRow_failsClosed() throws Exception {
            byte[] baselineBytes = generateBaseline(3);
            wireMocks(baselineBytes);

            Workbook uploaded = fromBytes(baselineBytes);
            Sheet up = uploaded.getSheet(SHEET);
            // delete the last pre-filled row (row index 2 -> sheet row 4) entirely
            up.removeRow(up.getRow(4));

            assertThrows(CustomException.class,
                    () -> join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap()),
                    "A deleted pre-filled row must fail closed (orphan)");
            uploaded.close();
        }

        @Test
        void endToEnd_identityMismatch_failsClosed() throws Exception {
            byte[] baselineBytes = generateBaseline(2);
            when(repo.findByGenerationId(GEN_ID, TENANT)).thenReturn(GenerateResource.builder()
                    .id(GEN_ID).fileStoreId(BASELINE_FS).referenceId("OTHER").type(TYPE).tenantId(TENANT).build());
            when(fileStore.downloadExcelFromFileStore(BASELINE_FS, TENANT)).thenReturn(fromBytes(baselineBytes));

            Workbook uploaded = fromBytes(baselineBytes);
            assertThrows(CustomException.class,
                    () -> join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap()),
                    "referenceId mismatch must fail closed");
            uploaded.close();
        }

        @Test
        void performance_generateAndJoin_10kRows_isLinearAndFast() throws Exception {
            int n = 10_000;
            config.setExcelRowLimit(100); // don't style extra empty rows beyond the data

            long t0 = System.currentTimeMillis();
            byte[] baselineBytes = generateBaseline(n);
            wireMocks(baselineBytes);

            Workbook uploaded = fromBytes(baselineBytes);
            Sheet up = uploaded.getSheet(SHEET);
            int cName = colIndex(up, "name");
            setCell(up, 2, cName, "HACKED");   // tamper one immutable cell

            join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap());
            long elapsed = System.currentTimeMillis() - t0;

            List<Map<String, Object>> rows = excelUtil.convertSheetToMapListCached(UPLOAD_FS, SHEET, up);
            assertEquals(n, rows.size(), "all rows present");
            assertEquals("Name0", rows.get(0).get("name"), "tampered immutable cell restored at scale");
            assertTrue(elapsed < 60_000, "generate+join of 10k rows should be well under 60s (was " + elapsed + "ms)");
            uploaded.close();
        }
    }
}
