package org.egov.excelingestion.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.egov.excelingestion.config.ErrorConstants;
import org.egov.excelingestion.config.ExcelIngestionConfig;
import org.egov.excelingestion.config.ProcessingConstants;
import org.egov.excelingestion.config.ValidationConstants;
import org.egov.excelingestion.constants.GenerationConstants;
import org.egov.excelingestion.exception.CustomExceptionHandler;
import org.egov.excelingestion.repository.GeneratedFileRepository;
import org.egov.excelingestion.util.CellProtectionManager;
import org.egov.excelingestion.util.ColumnDefMaker;
import org.egov.excelingestion.util.ExcelDataPopulator;
import org.egov.excelingestion.util.ExcelStyleHelper;
import org.egov.excelingestion.util.ExcelUtil;
import org.egov.excelingestion.util.SchemaColumnDefUtil;
import org.egov.excelingestion.web.models.CampaignSearchResponse;
import org.egov.excelingestion.web.models.GenerateResource;
import org.egov.excelingestion.web.models.ProcessResource;
import org.egov.excelingestion.web.models.ValidationError;
import org.egov.excelingestion.web.models.excel.ColumnDef;
import org.egov.tracer.model.CustomException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Tests for {@link ImmutableJoinService} - the server-authoritative join that reconstructs pre-filled
 * immutable cells from the original generated baseline (unprotected join mode).
 *
 * <p>Two nested suites:
 * <ul>
 *   <li>{@link Unit} - ExcelUtil is mocked so {@code convertSheetToMapListCached} returns controlled
 *       in-memory row maps; the test inspects those maps after the join to assert what was restored vs
 *       kept. Fast, focused on the join logic and fail-closed paths.</li>
 *   <li>{@link EndToEnd} - exercises the REAL components (no mocking of the populator/parser/join): a
 *       workbook is GENERATED by the real {@link ExcelDataPopulator}, edited as a user would, then run
 *       through the real {@link ImmutableJoinService}. Only the filestore + repository are mocked.</li>
 * </ul>
 */
class ImmutableJoinServiceTest {

    // ============================================================================================
    // Mocked unit tests: controlled in-memory row maps; asserts what the join restores vs keeps.
    // ExcelUtil's STATIC helpers (getValueAsString / getCellValueAsString) run for real.
    // ============================================================================================
    @Nested
    @ExtendWith(MockitoExtension.class)
    class Unit {

        @Mock private GeneratedFileRepository generatedFileRepository;
        @Mock private FileStoreService fileStoreService;
        @Mock private ExcelUtil excelUtil;
        @Mock private SchemaColumnDefUtil schemaColumnDefUtil;
        @Mock private ExcelIngestionConfig config;
        @Mock private CampaignService campaignService;

        private ImmutableJoinService service;

        private static final String TENANT = "mz";
        private static final String TYPE = "unified-console-validation"; // a join-mode family (also: attendanceRegister/attendanceRegisterAttendee)
        private static final String REF = "campaign-1";
        private static final String GEN_ID = "gen-1";
        private static final String UPLOAD_FS = "upload-fs";
        private static final String BASELINE_FS = "baseline-fs";
        private static final String SHEET = "Users";
        private static final String PROTECTED_SIBLING_SHEET = "Boundary List";
        private static final String ROW_ID = ProcessingConstants.ROW_ID_COLUMN_NAME;
        private static final String ROW_NUM = ProcessingConstants.ACTUAL_ROW_NUMBER_KEY;

        private Workbook uploadedWorkbook;
        private Workbook baselineWorkbook;
        private ProcessResource resource;
        private Map<String, Map<String, Object>> sheetNameToSchema;

        @BeforeEach
        void setUp() throws Exception {
            service = new ImmutableJoinService(generatedFileRepository, fileStoreService, excelUtil,
                    schemaColumnDefUtil, new ObjectMapper(), new CustomExceptionHandler(), config,
                    campaignService);

            uploadedWorkbook = new XSSFWorkbook();
            uploadedWorkbook.createSheet(SHEET);
            uploadedWorkbook.createSheet(GenerationConstants.META_SHEET_NAME)
                    .createRow(0).createCell(0).setCellValue(GEN_ID);

            baselineWorkbook = new XSSFWorkbook();
            baselineWorkbook.createSheet(SHEET);
            // A real join-mode workbook always carries at least one PROTECTED sheet (the pre-filled
            // Boundary List, plus every non-join-mode sheet). The join treats "unprotected" as
            // "free-entry" only when protection was applied somewhere, so the baseline must model that
            // or every sheet would read as area-immutable. Not in sheetNameToSchema, so it is never
            // joined - it exists purely to carry the protection signal.
            baselineWorkbook.createSheet(PROTECTED_SIBLING_SHEET).protectSheet("pw");

            resource = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).build();

            sheetNameToSchema = new HashMap<>();
            sheetNameToSchema.put(SHEET, new HashMap<>());

            lenient().when(generatedFileRepository.findByGenerationId(GEN_ID, TENANT)).thenReturn(
                    GenerateResource.builder().id(GEN_ID).fileStoreId(BASELINE_FS)
                            .referenceId(REF).type(TYPE).tenantId(TENANT).build());
            lenient().when(fileStoreService.downloadExcelFromFileStore(BASELINE_FS, TENANT)).thenReturn(baselineWorkbook);
            lenient().when(schemaColumnDefUtil.convertSchemaToColumnDefs(anyString())).thenReturn(columnDefs());
            // Not a cloned campaign (no additionalDetails) -> identity falls through to the referenceId check.
            lenient().when(campaignService.searchCampaignById(anyString(), anyString(), any()))
                    .thenReturn(CampaignSearchResponse.CampaignDetail.builder().id(REF).tenantId(TENANT).build());
        }

        // immutable: name (freezeColumn), village (freezeTillData), roles (freezeColumn = multi-select parent)
        // conditional: phone (freezeColumnIfFilled); editable: comment (no flag)
        private List<ColumnDef> columnDefs() {
            return Arrays.asList(
                    ColumnDef.builder().name("name").freezeColumn(true).build(),
                    ColumnDef.builder().name("village").freezeTillData(true).build(),
                    ColumnDef.builder().name("roles").freezeColumn(true).build(),
                    ColumnDef.builder().name("phone").freezeColumnIfFilled(true).build(),
                    ColumnDef.builder().name("comment").build());
        }

        private Map<String, Object> row(Object... kv) {
            Map<String, Object> m = new HashMap<>();
            for (int i = 0; i < kv.length; i += 2) {
                m.put((String) kv[i], kv[i + 1]);
            }
            return m;
        }

        /**
         * Marks the BASELINE sheet protected, i.e. NOT a free-entry (user-typed) sheet. Generation
         * leaves only the User/Facilities List unprotected in join mode, and the join reads the
         * baseline's protection flag to decide whether area levels may be changed. Tests that assert
         * the Boundary List contract must call this; tests for the User List must not.
         */
        private void protectBaselineSheet() {
            baselineWorkbook.getSheet(SHEET).protectSheet("pw");
        }

        /**
         * Leaves NO protected sheet in the baseline, modelling a deployment where
         * egov.excel.sheet.password is blank so ExcelDataPopulator.applyProtection protected nothing. The
         * unprotected flag then carries no information and the join must fail CLOSED. Drops the sibling
         * rather than un-protecting it: POI has no clean "remove protection" on an already-protected
         * sheet, and removing the sheet models the same observable state.
         */
        private void unprotectAllBaselineSheets() {
            int siblingIdx = baselineWorkbook.getSheetIndex(PROTECTED_SIBLING_SHEET);
            if (siblingIdx >= 0) {
                baselineWorkbook.removeSheetAt(siblingIdx);
            }
        }

        private void stubRows(List<Map<String, Object>> uploaded, List<Map<String, Object>> baseline) {
            when(excelUtil.convertSheetToMapListCached(eq(UPLOAD_FS), eq(SHEET), any())).thenReturn(uploaded);
            when(excelUtil.convertSheetToMapListCached(eq(BASELINE_FS), eq(SHEET), any())).thenReturn(baseline);
        }

        private void run() {
            service.applyImmutableBaseline(uploadedWorkbook, resource, sheetNameToSchema, null);
        }

        @Test
        void restoresImmutable_keepsEditable_andMultiSelectChildren() {
            Map<String, Object> up = row(ROW_ID, "r1",
                    "name", "HACKED", "village", "HACKED_V", "phone", "999",
                    "comment", "user note", "roles_MULTISELECT_1", "HACKED_ROLE", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1",
                    "name", "Real Name", "village", "V1", "phone", "111",
                    "comment", "orig", "roles_MULTISELECT_1", "ADMIN", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            run();

            assertEquals("Real Name", up.get("name"), "freezeColumn restored from baseline");
            assertEquals("V1", up.get("village"), "freezeTillData restored from baseline");
            assertEquals("111", up.get("phone"), "freezeColumnIfFilled (baseline filled) restored");
            assertEquals("ADMIN", up.get("roles_MULTISELECT_1"), "multi-select child restored from baseline");
            assertEquals("user note", up.get("comment"), "editable column kept from file");
            assertEquals(3, up.get(ROW_NUM), "uploaded row number is preserved");
        }

        // Regression: reconstruction must also correct the WORKBOOK CELLS, not just the parsed row-map.
        // Before this fix, a tampered locked cell (boundary code / hierarchy name) stayed visible and
        // unflagged in the processed output file even though validation used the correct baseline value.
        @Test
        void cellWriteback_overwritesTamperedCellsInWorkbookNotJustTheMap() {
            final String CODE = ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY;
            // Real cells on the uploaded sheet: header row 0 (names must match the map keys), a localized
            // label row 1, and the tampered data row at index 2 (=> ACTUAL_ROW_NUMBER_KEY 3).
            Sheet up = uploadedWorkbook.getSheet(SHEET);
            String[] headers = {"name", "village", CODE, ROW_ID};
            Row h = up.createRow(0);
            for (int c = 0; c < headers.length; c++) {
                h.createCell(c).setCellValue(headers[c]);
            }
            up.createRow(1);
            Row data = up.createRow(2);
            data.createCell(0).setCellValue("ok");
            data.createCell(1).setCellValue("TAMPERED_VILLAGE");
            data.createCell(2).setCellValue("FAKE_CODE");
            data.createCell(3).setCellValue("r1");

            Map<String, Object> upMap = row(ROW_ID, "r1", "name", "ok",
                    "village", "TAMPERED_VILLAGE", CODE, "FAKE_CODE", ROW_NUM, 3);
            Map<String, Object> baseMap = row(ROW_ID, "r1", "name", "ok",
                    "village", "RealVillage", CODE, "REAL_CODE", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(upMap)), new ArrayList<>(List.of(baseMap)));

            run();

            // map corrected (pre-existing behavior)
            assertEquals("RealVillage", upMap.get("village"), "map: freezeTillData village reconstructed");
            assertEquals("REAL_CODE", upMap.get(CODE), "map: boundary code reconstructed");
            // NEW: the workbook cell is corrected too -> processed output file no longer shows the tamper
            assertEquals("RealVillage", up.getRow(2).getCell(1).getStringCellValue(),
                    "cell: tampered village overwritten with baseline value in the workbook");
            assertEquals("REAL_CODE", up.getRow(2).getCell(2).getStringCellValue(),
                    "cell: tampered boundary code overwritten with baseline value in the workbook");
        }

        // #2: a reverted locked cell must emit a NON-FAILING warning (status=valid) naming the column/row,
        // and editable columns (unchanged) must NOT warn.
        @Test
        void revertedLockedCell_producesNonFailingWarning() {
            Map<String, Object> up = row(ROW_ID, "r1", "name", "TAMPERED", "village", "TAMPERED_V",
                    "comment", "kept", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1", "name", "RealName", "village", "RealV",
                    "comment", "orig", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            List<ValidationError> warnings = new ArrayList<>();
            service.applyImmutableBaseline(uploadedWorkbook, resource, sheetNameToSchema, null, warnings, null);

            assertEquals("RealName", up.get("name"), "tampered freezeColumn reverted");
            assertEquals("RealV", up.get("village"), "tampered freezeTillData reverted");
            assertEquals("kept", up.get("comment"), "editable column NOT touched");
            assertFalse(warnings.isEmpty(), "a revert warning is collected");
            assertTrue(warnings.stream().allMatch(w -> ValidationConstants.STATUS_VALID.equals(w.getStatus())),
                    "warnings are non-failing (status=valid) so the row still passes");
            assertTrue(warnings.stream().allMatch(w -> Integer.valueOf(3).equals(w.getRowNumber())),
                    "warning points at the tampered row (1-based)");
            Set<String> cols = new HashSet<>();
            warnings.forEach(w -> cols.add(w.getColumnName()));
            assertTrue(cols.contains("name") && cols.contains("village"), "both reverted columns warned");
            assertFalse(cols.contains("comment"), "editable column produced NO warning");
        }

        // reject-on-change (egov.excel.immutable-reject-on-change=true): editing a pre-filled immutable DATA
        // cell FAILS the whole upload instead of silently reverting it.
        @Test
        void rejectOnChange_tamperedImmutableCell_throws() {
            when(config.isImmutableRejectOnChange()).thenReturn(true);
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED", "village", "V1",
                    "comment", "kept", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1", "name", "RealName", "village", "V1",
                    "comment", "orig", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            CustomException ex = assertThrows(CustomException.class, this::run);
            assertEquals(ErrorConstants.IMMUTABLE_CELL_TAMPERED, ex.getCode(),
                    "a changed pre-filled cell is rejected, not reverted");
        }

        // reject-on-change: an unchanged pre-filled row with only the EDITABLE column edited passes (no throw).
        @Test
        void rejectOnChange_onlyEditableChanged_passes() {
            when(config.isImmutableRejectOnChange()).thenReturn(true);
            Map<String, Object> up = row(ROW_ID, "r1", "name", "RealName", "village", "V1",
                    "comment", "user changed this", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1", "name", "RealName", "village", "V1",
                    "comment", "orig", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            assertDoesNotThrow(this::run, "editing only the editable column must not be rejected");
            assertEquals("user changed this", up.get("comment"), "editable column change is kept");
        }

        // reject-on-change: a multi-select CHILD cell difference is NOT rejected (restored silently) to avoid
        // false rejects from harmless per-child ordering.
        @Test
        void rejectOnChange_multiSelectChildDiff_restoredNotRejected() {
            when(config.isImmutableRejectOnChange()).thenReturn(true);
            Map<String, Object> up = row(ROW_ID, "r1", "name", "RealName", "village", "V1",
                    "roles_MULTISELECT_1", "SOMETHING_ELSE", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1", "name", "RealName", "village", "V1",
                    "roles_MULTISELECT_1", "ADMIN", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            assertDoesNotThrow(this::run, "multi-select child diff is restored, not rejected");
            assertEquals("ADMIN", up.get("roles_MULTISELECT_1"), "multi-select child restored from baseline");
        }

        // must-fix: the facility active/inactive (usage) column is intentionally editable even when the schema
        // marks it freezeColumn -> toggling it must NOT be rejected under reject-on-change.
        @Test
        void rejectOnChange_facilityUsageColumn_isEditable_notRejected() {
            when(config.isImmutableRejectOnChange()).thenReturn(true);
            when(schemaColumnDefUtil.convertSchemaToColumnDefs(anyString())).thenReturn(Arrays.asList(
                    ColumnDef.builder().name("name").freezeColumn(true).build(),
                    ColumnDef.builder().name(ProcessingConstants.FACILITY_USAGE_COLUMN_KEY)
                            .freezeColumn(true).build()));
            Map<String, Object> up = row(ROW_ID, "r1", "name", "RealName",
                    ProcessingConstants.FACILITY_USAGE_COLUMN_KEY, "Inactive", ROW_NUM, 3);
            Map<String, Object> base = row(ROW_ID, "r1", "name", "RealName",
                    ProcessingConstants.FACILITY_USAGE_COLUMN_KEY, "Active", ROW_NUM, 3);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            assertDoesNotThrow(this::run, "facility usage is editable; toggling Active->Inactive is allowed");
            assertEquals("Inactive", up.get(ProcessingConstants.FACILITY_USAGE_COLUMN_KEY),
                    "facility usage kept from the uploaded file (not reverted)");
        }

        @Test
        void skipSet_excludesImmutableColumnAbsentFromBaseline() {
            // 'village' is freezeTillData (immutable) in the CURRENT schema, but this baseline row predates it
            // (no 'village' key). The join cannot reconstruct it, so it must NOT appear in the returned skip
            // set - otherwise the user's value would bypass validation. 'name' IS present and reconstructed.
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED", "village", "USER_TYPED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name"); // no 'village' key
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            Map<String, Set<String>> skip = service.applyImmutableBaseline(uploadedWorkbook, resource, sheetNameToSchema, null);

            assertEquals("Real Name", up.get("name"), "present immutable column restored from baseline");
            assertEquals("USER_TYPED", up.get("village"), "immutable column absent from baseline is NOT overwritten");
            Set<String> sheetSkip = skip.getOrDefault(SHEET, Collections.emptySet());
            assertTrue(sheetSkip.contains("name"), "actually-reconstructed column is in the skip set");
            assertFalse(sheetSkip.contains("village"), "column absent from baseline must NOT be in the skip set");
        }

        @Test
        void boundaryColumn_prefilled_editableOnFreeEntrySheet() {
            // Boundary/hierarchy columns ("HZ_COUNTRY" etc.) are dynamic - NOT in the schema columnDefs.
            // CONTRACT CHANGED (worker area change): on a FREE-ENTRY sheet (User/Facilities List, left
            // unprotected by generation) a prefilled boundary level the operator changed is now KEPT, so
            // an area correction survives the join. The old behaviour - restore to baseline - still applies
            // on protected sheets; see boundarySheet_noSchemaImmutableColumns_stillLocksBoundaryAndCode.
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok",
                    "HZ_COUNTRY", "HACKED_COUNTRY", "HZ_PROVINCE", "UserPicked");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok",
                    "HZ_COUNTRY", "Mozambique", "HZ_PROVINCE", null);
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("HACKED_COUNTRY", up.get("HZ_COUNTRY"),
                    "changed boundary level kept on a free-entry sheet (area correction survives)");
            assertEquals("UserPicked", up.get("HZ_PROVINCE"), "empty-baseline boundary level stays user-editable");
        }

        @Test
        void boundarySheet_noSchemaImmutableColumns_stillLocksBoundaryAndCode() {
            // Regression for the Boundary List leak: that sheet's MDMS schema has ONLY editable target
            // columns, so the derived immutable set is EMPTY. joinSheet used to return at `immutable.isEmpty()`
            // NOTE: the Boundary List is a PROTECTED sheet, so area levels stay locked there even though
            // they are now editable on the free-entry User List. The fixture must say so explicitly.
            // BEFORE the dynamic boundary-column locking ran, leaving prefilled boundary selections + the
            // derived code unprotected - a user could tamper them and the change would persist. The boundary
            // columns + code must still be reconstructed from the baseline on an all-editable-schema sheet;
            // only the genuine target column stays user-controlled.
            when(schemaColumnDefUtil.convertSchemaToColumnDefs(anyString()))
                    .thenReturn(List.of(ColumnDef.builder().name("target").build())); // no freeze flag -> immutable empty
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "target", "55",
                    "HZ_COUNTRY", "HACKED", "HZ_PROVINCE", "HACKEDPROV",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "FAKE_CODE");
            Map<String, Object> base = row(ROW_ID, "r1", "target", "10",
                    "HZ_COUNTRY", "Manland", "HZ_PROVINCE", "RealProv",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "ZQ_VILL_231");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));
            protectBaselineSheet(); // Boundary List is protected -> area levels stay locked here

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("Manland", up.get("HZ_COUNTRY"),
                    "boundary column reconstructed even when the schema has NO immutable columns");
            assertEquals("RealProv", up.get("HZ_PROVINCE"), "prefilled boundary level locked to baseline");
            assertEquals("ZQ_VILL_231", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived boundary code restored to baseline (tamper corrected) on a no-immutable-schema sheet");
            assertEquals("55", up.get("target"), "editable target column stays user-controlled");
        }

        @Test
        void boundaryCode_keptWhenUserChangesLevelOnFreeEntrySheet() {
            // CONTRACT CHANGED (worker area change): boundary fully prefilled (COUNTRY+PROVINCE), and the
            // operator changed a level. On a free-entry sheet that is a permitted area change, so the level
            // is kept AND the derived code is NOT reset to the baseline - otherwise the edit would be
            // silently reverted. In production the code cell is a live VLOOKUP recomputed from the new
            // selections; the literal below just stands in for "whatever the sheet formula produced".
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "HACK", "HZ_PROVINCE", "HACKPROV",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "WRONG_CODE");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("HACKPROV", up.get("HZ_PROVINCE"), "changed boundary level kept on a free-entry sheet");
            assertEquals("WRONG_CODE", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived code NOT reset to baseline once the area path changed");
        }

        @Test
        void boundaryCode_keptWhenUserDeepensBoundary() {
            // Baseline has only COUNTRY; PROVINCE empty -> user legitimately deepens (picks Maryland). The
            // derived code must reflect the user's deeper selection, NOT be reset to the baseline country code.
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_PROVINCE", null,
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("Maryland", up.get("HZ_PROVINCE"), "user-deepened (empty-baseline) level kept");
            assertEquals("HZ_MZ_MARYLAND", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived code kept for the user's deeper selection, not reset to baseline country code");
        }

        /**
         * REGRESSION - the free-entry relaxation must not be inferable from a workbook that was generated
         * with NO protection at all. ExcelDataPopulator.applyProtection skips protection entirely when
         * egov.excel.sheet.password is blank; if "unprotected" were taken at face value then EVERY sheet -
         * including the pre-filled Boundary List - would become area-editable and its hierarchy writable.
         * With nothing protected the flag carries no information, so the join must fail CLOSED and restore
         * the baseline area exactly as it did before the relaxation existed.
         */
        @Test
        void areaChange_rejectedWhenNothingInTheWorkbookIsProtected() {
            unprotectAllBaselineSheets();
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_VILLAGE", "VILLAGE_B",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_VILLAGE_B");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ", "HZ_VILLAGE", "VILLAGE_A",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_VILLAGE_A");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("VILLAGE_A", up.get("HZ_VILLAGE"),
                    "with no protected sheet anywhere the area must be restored from baseline, not trusted");
            assertEquals("HZ_MZ_VILLAGE_A", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived code must follow the restored baseline area");
        }

        /**
         * CASE 2 - sideways move at the same level (village A -> village B) on a free-entry sheet.
         * The changed level must survive the join and the derived code must NOT be reset to the
         * baseline, or the move is silently reverted to the area the worker was leaving.
         */
        @Test
        void areaChange_sidewaysAtSameLevel_keptOnFreeEntrySheet() {
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ",
                    "HZ_PROVINCE", "Montserrado",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MONTSERRADO");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ",
                    "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("Montserrado", up.get("HZ_PROVINCE"), "same-level move kept, not reverted to Maryland");
            assertEquals("HZ_MZ_MONTSERRADO", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived code follows the sideways move");
            assertEquals("MZ", up.get("HZ_COUNTRY"), "untouched ancestor level unchanged");
        }

        /**
         * CASE 3 - clearing a level (village -> blank) on a free-entry sheet. The cleared cell must
         * stay blank and the derived code must follow the now-shorter path, rather than the baseline's
         * deeper code being restored over it.
         */
        @Test
        void areaChange_clearingALevel_keptOnFreeEntrySheet() {
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ",
                    "HZ_PROVINCE", null,
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ",
                    "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertNull(up.get("HZ_PROVINCE"), "cleared level stays cleared, not restored");
            assertEquals("HZ_MZ", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "derived code follows the shorter path after the level was cleared");
        }

        /**
         * SCOPING GUARD. The same sideways move on a PROTECTED sheet (Boundary List) must still be
         * rejected/restored. This is the test that fails if the relaxation is ever widened beyond the
         * free-entry sheets again.
         */
        @Test
        void areaChange_sidewaysOnProtectedSheet_stillRestored() {
            ProcessResource res = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).hierarchyType("HZ").build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ",
                    "HZ_PROVINCE", "Montserrado",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MONTSERRADO");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "ok", "HZ_COUNTRY", "MZ",
                    "HZ_PROVINCE", "Maryland",
                    ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY, "HZ_MZ_MARYLAND");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));
            protectBaselineSheet();

            service.applyImmutableBaseline(uploadedWorkbook, res, sheetNameToSchema, null);

            assertEquals("Maryland", up.get("HZ_PROVINCE"), "protected sheet: changed level restored to baseline");
            assertEquals("HZ_MZ_MARYLAND", up.get(ProcessingConstants.BOUNDARY_CODE_COLUMN_KEY),
                    "protected sheet: derived code restored to baseline");
        }

        @Test
        void freezeColumnIfFilled_emptyBaseline_keepsUserInput() {
            Map<String, Object> up = row(ROW_ID, "r1", "name", "X", "phone", "user-typed");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "X", "phone", null); // empty -> editable
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            run();

            assertEquals("user-typed", up.get("phone"), "empty-baseline freezeColumnIfFilled cell stays editable");
        }

        @Test
        void newRow_withoutRowId_isTrustedVerbatim() {
            Map<String, Object> existing = row(ROW_ID, "r1", "name", "hack");
            Map<String, Object> newRow = row("name", "Brand New", "comment", "x"); // no row-id
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real");
            stubRows(new ArrayList<>(List.of(existing, newRow)), new ArrayList<>(List.of(base)));

            run();

            assertEquals("Real", existing.get("name"), "existing row immutable restored");
            assertEquals("Brand New", newRow.get("name"), "new row (no id) trusted verbatim");
        }

        @Test
        void unknownRowId_failsClosed() {
            stubRows(new ArrayList<>(List.of(row(ROW_ID, "ghost", "name", "x"))),
                    new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "Real"))));
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void duplicateRowId_failsClosed() {
            stubRows(new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "a"), row(ROW_ID, "r1", "name", "b"))),
                    new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "Real"))));
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void deletedRow_orphan_failsClosed() {
            // baseline has r1 + r2; upload has only r1 -> r2 is an orphan (deleted pre-filled row)
            stubRows(new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "a"))),
                    new ArrayList<>(List.of(row(ROW_ID, "r1", "name", "A"), row(ROW_ID, "r2", "name", "B"))));
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void identityMismatch_failsClosed() throws Exception {
            when(generatedFileRepository.findByGenerationId(GEN_ID, TENANT)).thenReturn(
                    GenerateResource.builder().id(GEN_ID).fileStoreId(BASELINE_FS)
                            .referenceId("OTHER-CAMPAIGN").type(TYPE).tenantId(TENANT).build());
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void baselineNotFound_failsClosed() throws Exception {
            when(generatedFileRepository.findByGenerationId(GEN_ID, TENANT)).thenReturn(null);
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void missingGenerationId_withRowIdColumn_failsClosed() {
            // Metadata sheet stripped, but the hidden row-id column remains -> tampering -> fail closed.
            removeMetaSheet();
            uploadedWorkbook.getSheet(SHEET).createRow(0).createCell(0)
                    .setCellValue(ProcessingConstants.ROW_ID_COLUMN_NAME);
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void missingGenerationId_noRowIdColumn_failsClosed() {
            // A join-mode upload MUST carry an embedded generationId (the generated template always has one).
            // A file lacking both the meta sheet and the row-id column is not the generated template for this
            // campaign -> fail closed. (Previously this was silently skipped as "legacy", which let arbitrary
            // non-generated files bypass immutability - now removed.)
            removeMetaSheet();
            assertThrows(CustomException.class, this::run);
        }

        @Test
        void outOfScopeType_skipsJoinEntirely() {
            // A type outside the join-mode families must be left completely untouched (no baseline lookup, no join).
            ProcessResource other = ProcessResource.builder()
                    .tenantId(TENANT).type("someUnrelatedType-validation").referenceId(REF).fileStoreId(UPLOAD_FS).build();
            assertDoesNotThrow(() -> service.applyImmutableBaseline(uploadedWorkbook, other, sheetNameToSchema, null));
            verifyNoInteractions(generatedFileRepository, fileStoreService);
        }

        @Test
        void attendanceRegisterType_isInScope_andJoins() {
            // attendanceRegister is a join-mode family -> immutable cells are reconstructed from the baseline.
            ProcessResource attendance = ProcessResource.builder()
                    .tenantId(TENANT).type("attendanceRegister-validation").referenceId(REF).fileStoreId(UPLOAD_FS).build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, attendance, sheetNameToSchema, null);

            assertEquals("Real Name", up.get("name"), "attendanceRegister type is in join scope -> immutable restored");
        }

        @Test
        void attendanceRegisterAttendeeType_isInScope_andJoins() {
            // attendanceRegisterAttendee is covered by the "attendanceRegister" prefix -> also in scope.
            ProcessResource attendee = ProcessResource.builder()
                    .tenantId(TENANT).type("attendanceRegisterAttendee-validation").referenceId(REF).fileStoreId(UPLOAD_FS).build();
            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, attendee, sheetNameToSchema, null);

            assertEquals("Real Name", up.get("name"), "attendanceRegisterAttendee type is in join scope -> immutable restored");
        }

        @Test
        void attendeeUpload_withRegisterReference_doesNotResolveReferenceAsCampaign() {
            // Attendee uploads send referenceType "attendanceRegister" and a REGISTER id. Resolving that
            // as a campaign throws CAMPAIGN_NOT_FOUND and blocks every attendee upload, so the lookup
            // must be skipped entirely for non-campaign references.
            lenient().when(campaignService.searchCampaignById(anyString(), anyString(), any()))
                    .thenThrow(new RuntimeException("Campaign not found with ID: register-1"));

            ProcessResource attendee = ProcessResource.builder()
                    .tenantId(TENANT).type("attendanceRegisterAttendee-validation")
                    .referenceId(REF).referenceType("attendanceRegister")
                    .fileStoreId(UPLOAD_FS).build();

            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, attendee, sheetNameToSchema, null);

            assertEquals("Real Name", up.get("name"), "attendee upload must join without a campaign lookup");
            verify(campaignService, never()).searchCampaignById(anyString(), anyString(), any());
        }

        @Test
        void campaignReference_stillResolvesClonedCampaign() {
            // The clone fix must keep working for campaign references: the baseline belongs to the
            // campaign this one was cloned FROM, not to this campaign's own id.
            when(campaignService.searchCampaignById(anyString(), anyString(), any()))
                    .thenReturn(CampaignSearchResponse.CampaignDetail.builder()
                            .id("campaign-2").tenantId(TENANT)
                            .additionalDetails(CampaignSearchResponse.AdditionalDetails.builder()
                                    .clonedCampaignId(REF).build())
                            .build());

            ProcessResource cloned = ProcessResource.builder()
                    .tenantId(TENANT).type(TYPE).referenceId("campaign-2")
                    .referenceType("campaign").fileStoreId(UPLOAD_FS).build();

            Map<String, Object> up = row(ROW_ID, "r1", "name", "HACKED");
            Map<String, Object> base = row(ROW_ID, "r1", "name", "Real Name");
            stubRows(new ArrayList<>(List.of(up)), new ArrayList<>(List.of(base)));

            service.applyImmutableBaseline(uploadedWorkbook, cloned, sheetNameToSchema, null);

            assertEquals("Real Name", up.get("name"), "cloned campaign baseline must still be accepted");
            verify(campaignService).searchCampaignById(anyString(), anyString(), any());
        }

        private void removeMetaSheet() {
            uploadedWorkbook.removeSheetAt(uploadedWorkbook.getSheetIndex(GenerationConstants.META_SHEET_NAME));
        }
    }

    // ============================================================================================
    // End-to-end integration: real ExcelDataPopulator generation -> user edits -> real join.
    // Only the filestore + repository boundaries are mocked. A memoizing spy on ExcelUtil reproduces
    // the production @Cacheable behaviour so the in-place mutation the join performs is observable.
    // ============================================================================================
    @Nested
    class EndToEnd {

        private static final String TENANT = "mz";
        private static final String TYPE = "unified-console-validation"; // a join-mode family (also: attendanceRegister/attendanceRegisterAttendee)
        private static final String REF = "campaign-1";
        private static final String GEN_ID = "gen-e2e-1";
        private static final String UPLOAD_FS = "upload-fs";
        private static final String BASELINE_FS = "baseline-fs";
        private static final String SHEET = "Users";
        private static final String USAGE = ProcessingConstants.USER_USAGE_COLUMN_KEY;

        private ExcelIngestionConfig config;
        private ExcelDataPopulator populator;
        private SchemaColumnDefUtil schemaColumnDefUtil;
        private ExcelUtil excelUtil;                 // memoizing spy
        private GeneratedFileRepository repo;
        private FileStoreService fileStore;
        private ImmutableJoinService join;

        private final Map<String, List<Map<String, Object>>> parseCache = new HashMap<>();

        @BeforeEach
        void setUp() {
            config = new ExcelIngestionConfig();
            config.setExcelSheetPassword("testpwd");   // a password IS configured; join mode must still skip protection
            config.setExcelRowLimit(100);
            config.setExcelSheetZoom(60);
            config.setValidationErrorColor("#ff0000");
            config.setServerTimezone("UTC");

            ExcelStyleHelper styleHelper = new ExcelStyleHelper();
            CellProtectionManager cpm = new CellProtectionManager(config, styleHelper);
            populator = new ExcelDataPopulator(config, styleHelper, cpm);

            CustomExceptionHandler exceptionHandler = new CustomExceptionHandler();
            schemaColumnDefUtil = new SchemaColumnDefUtil(new ColumnDefMaker(), exceptionHandler);

            excelUtil = spy(new ExcelUtil());
            // Reproduce @Cacheable: same (fileStoreId, sheetName) -> same list instance, so the join's
            // in-place mutation is visible when we re-fetch.
            doAnswer(inv -> {
                String key = inv.getArgument(0) + "|" + inv.getArgument(1);
                return parseCache.computeIfAbsent(key, k -> {
                    try {
                        @SuppressWarnings("unchecked")
                        List<Map<String, Object>> parsed = (List<Map<String, Object>>) inv.callRealMethod();
                        return parsed;
                    } catch (Throwable t) {
                        throw new RuntimeException(t);
                    }
                });
            }).when(excelUtil).convertSheetToMapListCached(anyString(), anyString(), any());

            repo = mock(GeneratedFileRepository.class);
            fileStore = mock(FileStoreService.class);
            // Not a cloned campaign (no additionalDetails) -> identity falls through to the referenceId check.
            CampaignService campaignService = mock(CampaignService.class);
            when(campaignService.searchCampaignById(anyString(), anyString(), any()))
                    .thenReturn(CampaignSearchResponse.CampaignDetail.builder().id(REF).tenantId(TENANT).build());
            join = new ImmutableJoinService(repo, fileStore, excelUtil, schemaColumnDefUtil,
                    new ObjectMapper(), exceptionHandler, config, campaignService);
        }

        // Schema: name (freezeColumn), village (freezeTillData), phone (freezeColumnIfFilled),
        // comment (editable), HCM_ADMIN_CONSOLE_USER_USAGE (freezeColumn in schema, but join-EXCLUDED -> editable).
        private String schemaJson() {
            return "{\"stringProperties\":["
                    + "{\"name\":\"name\",\"orderNumber\":1,\"freezeColumn\":true},"
                    + "{\"name\":\"village\",\"orderNumber\":2,\"freezeTillData\":true},"
                    + "{\"name\":\"phone\",\"orderNumber\":3,\"freezeColumnIfFilled\":true},"
                    + "{\"name\":\"comment\",\"orderNumber\":4},"
                    + "{\"name\":\"" + USAGE + "\",\"orderNumber\":5,\"freezeColumn\":true}"
                    + "]}";
        }

        private Map<String, Object> rowOf(String name, String village, String phone, String comment, String usage) {
            Map<String, Object> m = new HashMap<>();
            m.put("name", name);
            m.put("village", village);
            if (phone != null) m.put("phone", phone);
            m.put("comment", comment);
            m.put(USAGE, usage);
            return m;
        }

        private byte[] toBytes(Workbook wb) throws Exception {
            try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
                wb.write(bos);
                return bos.toByteArray();
            }
        }

        private Workbook fromBytes(byte[] bytes) throws Exception {
            return new XSSFWorkbook(new ByteArrayInputStream(bytes));
        }

        private int colIndex(Sheet sheet, String header) {
            Row r0 = sheet.getRow(0);
            for (int c = 0; c < r0.getLastCellNum(); c++) {
                Cell cell = r0.getCell(c);
                if (cell != null && header.equals(cell.getStringCellValue())) return c;
            }
            return -1;
        }

        private void setCell(Sheet sheet, int sheetRow, int col, String value) {
            Row r = sheet.getRow(sheetRow);
            if (r == null) r = sheet.createRow(sheetRow);
            Cell c = r.getCell(col);
            if (c == null) c = r.createCell(col);
            c.setCellValue(value);
        }

        /** Generates a join-mode baseline workbook with {@code n} pre-filled rows (phone empty on row index 1). */
        private byte[] generateBaseline(int n) throws Exception {
            List<ColumnDef> columns = schemaColumnDefUtil.convertSchemaToColumnDefs(schemaJson());
            List<Map<String, Object>> data = new ArrayList<>(n);
            for (int i = 0; i < n; i++) {
                String phone = (i == 1) ? null : ("100" + i);       // row index 1 has empty phone
                data.add(rowOf("Name" + i, "V" + i, phone, "c" + i, "Active"));
            }
            // 7-arg with joinMode=true, userEntrySheet=true: this baseline models the "Users" (User List)
            // sheet, a free-entry console sheet that must stay UNPROTECTED so copy-paste works; immutability
            // is enforced by the server-side join, verified below. (The 5-arg overload defaults to protected.)
            Workbook wb = populator.populateSheetWithData(new XSSFWorkbook(), SHEET, columns, data, new HashMap<>(), true, true);
            // Mirror ConfigBasedGenerationService: embed the generationId in the hidden meta sheet.
            wb.createSheet(GenerationConstants.META_SHEET_NAME).createRow(0).createCell(0).setCellValue(GEN_ID);
            return toBytes(wb);
        }

        private void wireMocks(byte[] baselineBytes) throws Exception {
            when(repo.findByGenerationId(GEN_ID, TENANT)).thenReturn(GenerateResource.builder()
                    .id(GEN_ID).fileStoreId(BASELINE_FS).referenceId(REF).type(TYPE).tenantId(TENANT).build());
            when(fileStore.downloadExcelFromFileStore(BASELINE_FS, TENANT)).thenReturn(fromBytes(baselineBytes));
        }

        private Map<String, Map<String, Object>> sheetSchemaMap() throws Exception {
            Map<String, Map<String, Object>> m = new HashMap<>();
            m.put(SHEET, new ObjectMapper().readValue(schemaJson(), Map.class));
            return m;
        }

        private ProcessResource resource() {
            return ProcessResource.builder().tenantId(TENANT).type(TYPE).referenceId(REF).fileStoreId(UPLOAD_FS).build();
        }

        @Test
        void generatedTemplate_isUnprotected_andHasHiddenRowIdColumn() throws Exception {
            byte[] bytes = generateBaseline(3);
            Workbook wb = fromBytes(bytes);
            Sheet sheet = wb.getSheet(SHEET);

            // R1: copy-paste works -> the sheet must NOT be protected, even though a password is configured.
            assertFalse(sheet.getProtect(), "Join-mode generated sheet must be unprotected");

            int idCol = colIndex(sheet, ProcessingConstants.ROW_ID_COLUMN_NAME);
            assertTrue(idCol >= 0, "Hidden row-id column must be stamped");
            assertTrue(sheet.isColumnHidden(idCol), "Row-id column must be hidden");
            assertFalse(sheet.getRow(2).getCell(idCol).getStringCellValue().isEmpty(), "Each pre-filled row gets a row-id");
            assertNotNull(wb.getSheet(GenerationConstants.META_SHEET_NAME), "generationId meta sheet present");
            wb.close();
        }

        @Test
        void endToEnd_restoresTamperedImmutable_keepsEditable_allowsNewRow() throws Exception {
            byte[] baselineBytes = generateBaseline(3);
            wireMocks(baselineBytes);

            Workbook uploaded = fromBytes(baselineBytes);
            Sheet up = uploaded.getSheet(SHEET);
            int cName = colIndex(up, "name");
            int cVillage = colIndex(up, "village");
            int cPhone = colIndex(up, "phone");
            int cComment = colIndex(up, "comment");
            int cUsage = colIndex(up, USAGE);

            // --- user/attacker edits on the unprotected sheet ---
            setCell(up, 2, cName, "HACKED");        // row0 immutable freezeColumn  -> must be restored
            setCell(up, 2, cUsage, "Inactive");     // row0 active/inactive          -> editable, must be KEPT
            setCell(up, 3, cPhone, "999");          // row1 phone (baseline empty)   -> editable, must be KEPT
            setCell(up, 4, cVillage, "HACKED_V");   // row2 freezeTillData           -> must be restored
            // new row at sheet row 5 (no row-id) -> trusted as new
            setCell(up, 5, cName, "NewGuy");
            setCell(up, 5, cComment, "brand new");

            join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap(), null);

            List<Map<String, Object>> rows = excelUtil.convertSheetToMapListCached(UPLOAD_FS, SHEET, up);
            assertEquals(4, rows.size(), "3 existing + 1 new row");

            assertEquals("Name0", rows.get(0).get("name"), "freezeColumn tamper restored from baseline");
            assertEquals("Inactive", rows.get(0).get(USAGE), "active/inactive column kept (excluded from join)");
            assertEquals("999", rows.get(1).get("phone"), "freezeColumnIfFilled with empty baseline -> user value kept");
            assertEquals("V2", rows.get(2).get("village"), "freezeTillData tamper restored from baseline");
            assertEquals("NewGuy", rows.get(3).get("name"), "new row trusted verbatim");
            assertNull(rows.get(3).get(ProcessingConstants.ROW_ID_COLUMN_NAME), "new row has no row-id");

            uploaded.close();
        }

        @Test
        void endToEnd_deletedPreFilledRow_failsClosed() throws Exception {
            byte[] baselineBytes = generateBaseline(3);
            wireMocks(baselineBytes);

            Workbook uploaded = fromBytes(baselineBytes);
            Sheet up = uploaded.getSheet(SHEET);
            // delete the last pre-filled row (row index 2 -> sheet row 4) entirely
            up.removeRow(up.getRow(4));

            assertThrows(CustomException.class,
                    () -> join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap(), null),
                    "A deleted pre-filled row must fail closed (orphan)");
            uploaded.close();
        }

        @Test
        void endToEnd_identityMismatch_failsClosed() throws Exception {
            byte[] baselineBytes = generateBaseline(2);
            when(repo.findByGenerationId(GEN_ID, TENANT)).thenReturn(GenerateResource.builder()
                    .id(GEN_ID).fileStoreId(BASELINE_FS).referenceId("OTHER").type(TYPE).tenantId(TENANT).build());
            when(fileStore.downloadExcelFromFileStore(BASELINE_FS, TENANT)).thenReturn(fromBytes(baselineBytes));

            Workbook uploaded = fromBytes(baselineBytes);
            assertThrows(CustomException.class,
                    () -> join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap(), null),
                    "referenceId mismatch must fail closed");
            uploaded.close();
        }

        @Test
        void performance_generateAndJoin_10kRows_isLinearAndFast() throws Exception {
            int n = 10_000;
            config.setExcelRowLimit(100); // don't style extra empty rows beyond the data

            long t0 = System.currentTimeMillis();
            byte[] baselineBytes = generateBaseline(n);
            wireMocks(baselineBytes);

            Workbook uploaded = fromBytes(baselineBytes);
            Sheet up = uploaded.getSheet(SHEET);
            int cName = colIndex(up, "name");
            setCell(up, 2, cName, "HACKED");   // tamper one immutable cell

            join.applyImmutableBaseline(uploaded, resource(), sheetSchemaMap(), null);
            long elapsed = System.currentTimeMillis() - t0;

            List<Map<String, Object>> rows = excelUtil.convertSheetToMapListCached(UPLOAD_FS, SHEET, up);
            assertEquals(n, rows.size(), "all rows present");
            assertEquals("Name0", rows.get(0).get("name"), "tampered immutable cell restored at scale");
            assertTrue(elapsed < 60_000, "generate+join of 10k rows should be well under 60s (was " + elapsed + "ms)");
            uploaded.close();
        }
    }
}
