openapi: 3.0.1
info:
  title: Household Registry
  version: v1.6
servers:
  - url: https://unified-dev.digit.org
    description: Development server url
paths:
  /v1/_create:
    post:
      tags:
        - Product
      summary: Create/Add a new product
      description: Create/Add a new product
      operationId: productV1CreatePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /v1/_update:
    post:
      tags:
        - Product
      summary: Update product
      description: Update product
      operationId: productV1UpdatePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /v1/_search:
    post:
      tags:
        - Product
      summary: Search product
      description: Search product
      operationId: productV1SearchPost
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            maximum: 1000
            minimum: 0
            type: integer
            format: int32
        - name: offset
          in: query
          required: true
          schema:
            minimum: 0
            type: integer
            format: int32
        - name: tenantId
          in: query
          required: true
          schema:
            maxLength: 1000
            minLength: 2
            type: string
        - name: lastChangedSince
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: includeDeleted
          in: query
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSearchRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /variant/v1/_create:
    post:
      tags:
        - Product Variant
      summary: Create/Add a new variant for a product
      description: Create/Add a new variant for a product
      operationId: productVariantV1CreatePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductVariantRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductVariantResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /variant/v1/_update:
    post:
      tags:
        - Product Variant
      summary: Update product variant
      description: Update product variant
      operationId: productVariantV1UpdatePost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductVariantRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductVariantResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
  /variant/v1/_search:
    post:
      tags:
        - Product Variant
      summary: Search product variant
      description: Search product variant
      operationId: productVariantV1SearchPost
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            maximum: 1000
            minimum: 0
            type: integer
            format: int32
        - name: offset
          in: query
          required: true
          schema:
            minimum: 0
            type: integer
            format: int32
        - name: tenantId
          in: query
          required: true
          schema:
            maxLength: 1000
            minLength: 2
            type: string
        - name: lastChangedSince
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: includeDeleted
          in: query
          required: false
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductVariantSearchRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductVariantResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes
components:
  schemas:
    AdditionalFields:
      type: object
      properties:
        schema:
          maxLength: 64
          minLength: 2
          type: string
        version:
          minimum: 1
          type: integer
          format: int32
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    AuditDetails:
      type: object
      properties:
        createdBy:
          type: string
        lastModifiedBy:
          type: string
        createdTime:
          type: integer
          format: int64
        lastModifiedTime:
          type: integer
          format: int64
    Field:
      required:
        - key
        - value
      type: object
      properties:
        key:
          maxLength: 64
          minLength: 2
          type: string
        value:
          maxLength: 10000
          minLength: 2
          type: string
    PlainAccessRequest:
      type: object
      properties:
        recordId:
          type: string
        plainRequestFields:
          type: array
          items:
            type: string
    ProductVariant:
      required:
        - productId
        - tenantId
        - variation
      type: object
      properties:
        id:
          type: string
        tenantId:
          maxLength: 1000
          minLength: 2
          type: string
        productId:
          maxLength: 64
          minLength: 2
          type: string
        sku:
          maxLength: 1000
          minLength: 0
          type: string
        variation:
          maxLength: 1000
          minLength: 0
          type: string
        additionalFields:
          $ref: '#/components/schemas/AdditionalFields'
        isDeleted:
          type: boolean
        rowVersion:
          type: integer
          format: int32
        auditDetails:
          $ref: '#/components/schemas/AuditDetails'
    ProductVariantRequest:
      required:
        - ProductVariant
        - RequestInfo
      type: object
      properties:
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
        ProductVariant:
          maxItems: 2147483647
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/ProductVariant'
        apiOperation:
          type: string
          enum:
            - CREATE
            - UPDATE
            - DELETE
    RequestInfo:
      type: object
      properties:
        apiId:
          type: string
        ver:
          type: string
        ts:
          type: integer
          format: int64
        action:
          type: string
        did:
          type: string
        key:
          type: string
        msgId:
          type: string
        authToken:
          type: string
        correlationId:
          type: string
        plainAccessRequest:
          $ref: '#/components/schemas/PlainAccessRequest'
        userInfo:
          $ref: '#/components/schemas/User'
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 128
          minLength: 0
          type: string
        code:
          maxLength: 50
          minLength: 0
          type: string
        tenantId:
          maxLength: 256
          minLength: 0
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userName:
          maxLength: 180
          minLength: 0
          type: string
        name:
          maxLength: 250
          minLength: 0
          type: string
        type:
          maxLength: 50
          minLength: 0
          type: string
        mobileNumber:
          maxLength: 150
          minLength: 0
          type: string
        emailId:
          maxLength: 300
          minLength: 0
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        tenantId:
          maxLength: 256
          minLength: 0
          type: string
        uuid:
          maxLength: 36
          minLength: 0
          type: string
    ProductVariantResponse:
      required:
        - ProductVariant
        - ResponseInfo
      type: object
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        ProductVariant:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariant'
    ResponseInfo:
      type: object
      properties:
        apiId:
          type: string
        ver:
          type: string
        ts:
          type: integer
          format: int64
        resMsgId:
          type: string
        msgId:
          type: string
        status:
          type: string
    ProductVariantSearch:
      type: object
      properties:
        id:
          type: array
          items:
            type: string
        productId:
          maxLength: 64
          minLength: 2
          type: string
        sku:
          maxLength: 1000
          minLength: 0
          type: string
        variation:
          maxLength: 1000
          minLength: 0
          type: string
    ProductVariantSearchRequest:
      required:
        - ProductVariant
        - RequestInfo
      type: object
      properties:
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
        ProductVariant:
          $ref: '#/components/schemas/ProductVariantSearch'
    Product:
      required:
        - name
        - tenantId
        - type
      type: object
      properties:
        id:
          type: string
        tenantId:
          maxLength: 1000
          minLength: 2
          type: string
        type:
          maxLength: 100
          minLength: 2
          type: string
        name:
          maxLength: 1000
          minLength: 2
          type: string
        manufacturer:
          maxLength: 1000
          minLength: 0
          type: string
        additionalFields:
          $ref: '#/components/schemas/AdditionalFields'
        isDeleted:
          type: boolean
        rowVersion:
          type: integer
          format: int32
        auditDetails:
          $ref: '#/components/schemas/AuditDetails'
    ProductRequest:
      required:
        - Product
        - RequestInfo
      type: object
      properties:
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
        Product:
          maxItems: 2147483647
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/Product'
        apiOperation:
          type: string
          enum:
            - CREATE
            - UPDATE
            - DELETE
    ProductResponse:
      required:
        - Product
        - ResponseInfo
      type: object
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        Product:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    ProductSearch:
      type: object
      properties:
        id:
          type: array
          items:
            type: string
        type:
          type: string
        name:
          type: string
        manufacturer:
          type: string
    ProductSearchRequest:
      required:
        - Product
        - RequestInfo
      type: object
      properties:
        RequestInfo:
          $ref: '#/components/schemas/RequestInfo'
        Product:
          $ref: '#/components/schemas/ProductSearch'

