ALTER TABLE PRODUCT DROP COLUMN IF EXISTS clientCreatedTime bigint;
ALTER TABLE PRODUCT DROP COLUMN IF EXISTS clientLastModifiedTime bigint;

ALTER TABLE PRODUCT_VARIANT DROP COLUMN IF EXISTS clientCreatedTime bigint;
ALTER TABLE PRODUCT_VARIANT DROP COLUMN IF EXISTS clientLastModifiedTime bigint;