services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Internal listener for Docker network
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      # Advertised listeners so that outside clients can connect and internal services can use the internal address
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"   # internal use by other services in Docker network
      - "9093:9093"   # exposed for external/debug/dev usage

  persister:
    # Use the LTS version of DIGIT Persister
    image: egovio/egov-persister:DIGIT-2.9-LTS-07f47790b8-8
    depends_on:
      - postgres
      - kafka
    environment:
      # Database connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # Kafka broker - internal address
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093

      # Persister configuration yaml(s) repository path
      # Use `file://` prefix pointing to mounted config directory in container
      EGOV_PERSIST_YML_REPO_PATH: file:///work-dir/config/persister-config.yml

    volumes:
      # Mount local persister config file
      - ./health-services/stock/src/main/resources/stock-persister.yml:/work-dir/config/persister-config.yml:ro

volumes:
  pgdata:
