export const facilityJsonData = [
    {
      "facility_name": "test_facility1",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h001",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility2",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h002",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility3",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h003",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility4",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h003",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility5",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h002",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility6",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h010",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility7",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h011",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility8",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h012",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility9",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h002",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility10",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h012",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility11",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h004",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    },
    {
      "facility_name": "test_facility12",
      "is_permanent": false,
      "facility_type": "Monitor Local",
      "boundary_code": "h005",
      "administrative_area": "tete",
      "address_line_1": "",
      "address_line_2": "",
      "landmark": "",
      "city": "",
      "pincode": 0,
      "building_name": "",
      "street": "",
      "storage": 0,
      "latitude": 0,
      "longitude": 0,
      "parent_code": "",
      "uuid": "",
      "target": 1
    }
  ];
  