export const userJsonData = [
  {
    "username": "emp400",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456789",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h002",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp401",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456790",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h012",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp402",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456791",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h003",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp403",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456792",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h002",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp404",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456793",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h007",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp405",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456794",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h006",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp406",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456795",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "PERMANENT",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h004",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  },
  {
    "username": "emp407",
    "password": "eGov@123",
    "name": "Testing Ingestion",
    "mobile_number": "6123456796",
    "gender": "",
    "date_of_birth": "",
    "email": "",
    "correspondence_address": "",
    "roles": "SYSTEM_ADMINISTRATOR",
    "employment_type": "TEMPORARY",
    "date_of_joining": "10/01/2024",
    "department": "OTHER",
    "designation": "",
    "campaign_name": "LLINMozambique2",
    "administrative_area": "Gaza",
    "boundary_code": "h002",
    "insert_time": "2023-10-29 13:47:16",
    "update_time": "2023-10-29 13:47:16",
    "filename": "<DirEntry 'Microplano Chongoene.xlsx'>"
  }
]
