serviceMaps:
  serviceName: IDGENERATOR
  mappings:
    - version: 1.0
      name: idpool
      description: Persists a batch of unique IDs into the id_pool table
      fromTopic: save-in-id-pool
      isTransaction: true
      queryMaps:
        - query: INSERT INTO id_pool (id, status, tenantId, additionalFields, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion)
            VALUES (?, 'UNASSIGNED', ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (id) DO NOTHING;
          basePath: $.idPool.*
          jsonMaps:
            - jsonPath: $.idPool.*.id
            - jsonPath: $.idPool.*.tenantId
            - jsonPath: $.idPool.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.idPool.*.auditDetails.createdBy
            - jsonPath: $.idPool.*.auditDetails.lastModifiedBy
            - jsonPath: $.idPool.*.auditDetails.createdTime
            - jsonPath: $.idPool.*.auditDetails.lastModifiedTime
            - jsonPath: $.idPool.*.rowVersion

    - version: 1.0
      name: idpool-status-update
      description: Updates status of IDs dynamically
      fromTopic: update-id-pool-status
      isTransaction: true
      queryMaps:
        - query: |
            UPDATE id_pool SET status = ?, lastModifiedBy = ?, lastModifiedTime = ?, additionalFields = ?
            WHERE id = ?;
          basePath: $.idPool.*
          jsonMaps:
            - jsonPath: $.idPool.*.status
            - jsonPath: $.idPool.*.auditDetails.lastModifiedBy
            - jsonPath: $.idPool.*.auditDetails.lastModifiedTime
            - jsonPath: $.idPool.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.idPool.*.id

