serviceMaps:
  serviceName: IDGENERATOR
  mappings:
    - version: 1.0
      name: dispatch-log
      description: Logs dispatched ID transaction
      fromTopic: save-dispatch-id-log
      isTransaction: true
      queryMaps:
        - query: INSERT INTO id_transaction_log(id_reference, user_uuid, device_uuid, device_info, status, tenantId, additionalFields, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion)
            VALUES (?, ?, ?, ? , ? , ? , ?, ?, ?, ?, ?, ?)

          basePath: $.idTransactionLog.*
          jsonMaps:
            - jsonPath: $.idTransactionLog.*.id
            - jsonPath: $.idTransactionLog.*.userUuid
            - jsonPath: $.idTransactionLog.*.deviceUuid
            - jsonPath: $.idTransactionLog.*.deviceInfo
              type: JSON
              dbType: JSONB
            - jsonPath: $.idTransactionLog.*.status
            - jsonPath: $.idTransactionLog.*.tenantId
            - jsonPath: $.idTransactionLog.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.idTransactionLog.*.auditDetails.createdBy
            - jsonPath: $.idTransactionLog.*.auditDetails.lastModifiedBy
            - jsonPath: $.idTransactionLog.*.auditDetails.createdTime
            - jsonPath: $.idTransactionLog.*.auditDetails.lastModifiedTime
            - jsonPath: $.idTransactionLog.*.rowVersion
