"""
Configuration for Raw Event -> Bronze extraction.

Each entry represents one independent:

    Raw Event table -> Bronze table

To add a new table:

1. Create the Raw table.
2. Create the Bronze table.
3. Add one configuration entry here.
4. The DAG automatically creates a mapped task for it.

No DAG code changes are required.

Keys per entry:

    name          Table key. Also the map index shown in the Airflow UI.
    raw_table     Fully qualified event store table.
    bronze_table  Fully qualified stg_* table.
    page_size     Raw events read per keyset page.
    columns       Debezium `after` key -> Bronze column. Both sides are
                  validated at run time: every Bronze column must exist in
                  system.columns, and every configured source key must appear
                  in the actual event payload. A typo fails the task instead of
                  silently loading ''/0/False.

Optional:

    allow_null_after   Default False. The processor fails a table if any raw
                       event has a null `after`, because only CREATE and UPDATE
                       are expected here and both carry a row image -- a null
                       one is silent data loss. Set True only to deliberately
                       accept that loss and let the table proceed.
"""


RAW_EVENT_BRONZE_TABLES = [
    {
        "name": "household",
        "raw_table": "analytics.household_events_raw",
        "bronze_table": "analytics.stg_household",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "clientreferenceid": "client_reference_id",
            "numberofmembers": "member_count",
            "householdtype": "household_type",
            "addressid": "address_id",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "project_task",
        "raw_table": "analytics.project_task_events_raw",
        "bronze_table": "analytics.stg_project_task",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "projectbeneficiaryid": "project_beneficiary_id",
            "projectbeneficiaryclientreferenceid": "project_beneficiary_client_reference_id",
            "plannedstartdate": "planned_start_date",
            "plannedenddate": "planned_end_date",
            "actualstartdate": "actual_start_date",
            "actualenddate": "actual_end_date",
            "addressid": "address_id",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "status": "status",
        },
    },

    {
        "name": "address",
        "raw_table": "analytics.address_events_raw",
        "bronze_table": "analytics.stg_address",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "doorno": "door_no",
            "latitude": "latitude",
            "longitude": "longitude",
            "locationaccuracy": "location_accuracy",
            "type": "type",
            "addressline1": "address_line1",
            "addressline2": "address_line2",
            "landmark": "landmark",
            "city": "city",
            "pincode": "pincode",
            "buildingname": "building_name",
            "street": "street",
            "localitycode": "locality_code",
            "clientreferenceid": "client_reference_id",
            "wardcode": "ward_code",
        },
    },

    {
        "name": "individual",
        "raw_table": "analytics.individual_events_raw",
        "bronze_table": "analytics.stg_individual",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "userid": "user_id",
            "useruuid": "user_uuid",
            "clientreferenceid": "client_reference_id",
            "individualid": "individual_id",
            "tenantid": "tenant_id",
            "givenname": "given_name",
            "familyname": "family_name",
            "othernames": "other_names",
            "dateofbirth": "date_of_birth",
            "gender": "gender",
            "bloodgroup": "blood_group",
            "mobilenumber": "mobile_number",
            "altcontactnumber": "alt_contact_number",
            "email": "email",
            "fathername": "father_name",
            "husbandname": "husband_name",
            "relationship": "relationship",
            "photo": "photo",
            "type": "type",
            "username": "user_name",
            "roles": "roles",
            "issystemuser": "is_system_user",
            "issystemuseractive": "is_system_user_active",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "product",
        "raw_table": "analytics.product_events_raw",
        "bronze_table": "analytics.stg_product",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "type": "type",
            "name": "name",
            "manufacturer": "manufacturer",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "product_variant",
        "raw_table": "analytics.product_variant_events_raw",
        "bronze_table": "analytics.stg_product_variant",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "productid": "product_id",
            "sku": "sku",
            "variation": "variation",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "project",
        "raw_table": "analytics.project_events_raw",
        "bronze_table": "analytics.stg_project",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "projectnumber": "project_number",
            "name": "name",
            "projecttypeid": "project_type_id",
            "projecttype": "project_type",
            "projectsubtype": "project_sub_type",
            "department": "department",
            "description": "description",
            "referenceid": "reference_id",
            "natureofwork": "nature_of_work",
            "addressid": "address_id",
            "startdate": "start_date",
            "enddate": "end_date",
            "istaskenabled": "is_task_enabled",
            "parent": "parent",
            "projecthierarchy": "project_hierarchy",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "facility",
        "raw_table": "analytics.facility_events_raw",
        "bronze_table": "analytics.stg_facility",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "clientreferenceid": "client_reference_id",
            "ispermanent": "is_permanent",
            "name": "name",
            "usage": "usage",
            "storagecapacity": "storage_capacity",
            "addressid": "address_id",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "project_target",
        "raw_table": "analytics.project_target_events_raw",
        "bronze_table": "analytics.stg_project_target",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "projectid": "project_id",
            "beneficiarytype": "beneficiary_type",
            "totalno": "total_no",
            "targetno": "target_no",
            "isdeleted": "is_deleted",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
        },
    },

    {
        "name": "project_address",
        "raw_table": "analytics.project_address_events_raw",
        "bronze_table": "analytics.stg_project_address",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "doorno": "door_no",
            "latitude": "latitude",
            "longitude": "longitude",
            "locationaccuracy": "location_accuracy",
            "type": "type",
            "addressline1": "address_line1",
            "addressline2": "address_line2",
            "landmark": "landmark",
            "city": "city",
            "pincode": "pincode",
            "buildingname": "building_name",
            "street": "street",
            "boundary": "boundary",
            "boundarytype": "boundary_type",
        },
    },

    {
        "name": "project_staff",
        "raw_table": "analytics.project_staff_events_raw",
        "bronze_table": "analytics.stg_project_staff",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "staffid": "staff_id",
            "startdate": "start_date",
            "enddate": "end_date",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "project_facility",
        "raw_table": "analytics.project_facility_events_raw",
        "bronze_table": "analytics.stg_project_facility",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "facilityid": "facility_id",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "project_beneficiary",
        "raw_table": "analytics.project_beneficiary_events_raw",
        "bronze_table": "analytics.stg_project_beneficiary",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "beneficiaryid": "beneficiary_id",
            "clientreferenceid": "client_reference_id",
            "beneficiaryclientreferenceid": "beneficiary_client_reference_id",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "dateofregistration": "date_of_registration",
            "additionaldetails": "additional_details",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "tag": "tag",
        },
    },

    {
        "name": "stock",
        "raw_table": "analytics.stock_events_raw",
        "bronze_table": "analytics.stg_stock",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "facilityid": "facility_id",
            "productvariantid": "product_variant_id",
            "quantity": "quantity",
            "waybillnumber": "waybill_number",
            "dateofentry": "date_of_entry",
            "campaignnumber": "campaign_number",
            "referenceid": "reference_id",
            "referenceidtype": "reference_id_type",
            "transactiontype": "transaction_type",
            "transactionreason": "transaction_reason",
            "transactingpartyid": "transacting_party_id",
            "transactingpartytype": "transacting_party_type",
            "sendertype": "sender_type",
            "senderid": "sender_id",
            "receivertype": "receiver_type",
            "receiverid": "receiver_id",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "stock_reconciliation_log",
        "raw_table": "analytics.stock_reconciliation_events_raw",
        "bronze_table": "analytics.stg_stock_reconciliation",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "facilityid": "facility_id",
            "productvariantid": "product_variant_id",
            "referenceid": "reference_id",
            "referenceidtype": "reference_id_type",
            "dateofreconciliation": "date_of_reconciliation",
            "calculatedcount": "calculated_count",
            "physicalrecordedcount": "physical_recorded_count",
            "commentsonreconciliation": "comments_on_reconciliation",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "task_resource",
        "raw_table": "analytics.task_resource_events_raw",
        "bronze_table": "analytics.stg_task_resource",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "productvariantid": "product_variant_id",
            "taskid": "task_id",
            "quantity": "quantity",
            "isdelivered": "is_delivered",
            "reasonifnotdelivered": "reason_if_not_delivered",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "isdeleted": "is_deleted",
            "clientreferenceid": "client_reference_id",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "eg_pgr_service_v2",
        "raw_table": "analytics.pgr_service_events_raw",
        "bronze_table": "analytics.stg_pgr_service",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "servicecode": "service_code",
            "servicerequestid": "service_request_id",
            "description": "description",
            "accountid": "account_id",
            "additionaldetails": "additional_details",
            "applicationstatus": "application_status",
            "rating": "rating",
            "source": "source",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "active": "active",
            "selfcomplaint": "self_complaint",
            "hierarchytype": "hierarchy_type",
        },
    },

    {
        "name": "eg_pgr_address_v2",
        "raw_table": "analytics.pgr_address_events_raw",
        "bronze_table": "analytics.stg_pgr_address",
        "page_size": 10000,
        "columns": {
            "tenantid": "tenant_id",
            "id": "id",
            "parentid": "parent_id",
            "doorno": "door_no",
            "plotno": "plot_no",
            "buildingname": "building_name",
            "street": "street",
            "landmark": "landmark",
            "city": "city",
            "pincode": "pincode",
            "locality": "locality",
            "district": "district",
            "region": "region",
            "state": "state",
            "country": "country",
            "latitude": "latitude",
            "longitude": "longitude",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "eg_wms_attendance_register",
        "raw_table": "analytics.attendance_register_events_raw",
        "bronze_table": "analytics.stg_attendance_register",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "registernumber": "register_number",
            "name": "name",
            "startdate": "start_date",
            "enddate": "end_date",
            "status": "status",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "referenceid": "reference_id",
            "servicecode": "service_code",
            "localitycode": "locality_code",
            "reviewstatus": "review_status",
            "period_statuses": "period_statuses",
            "campaignnumber": "campaign_number",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "eg_wms_attendance_staff",
        "raw_table": "analytics.attendance_staff_events_raw",
        "bronze_table": "analytics.stg_attendance_staff",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "individual_id": "individual_id",
            "register_id": "register_id",
            "tenantid": "tenant_id",
            "enrollment_date": "enrollment_date",
            "deenrollment_date": "deenrollment_date",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "stafftype": "staff_type",
        },
    },

    {
        "name": "eg_wms_attendance_attendee",
        "raw_table": "analytics.attendance_attendee_events_raw",
        "bronze_table": "analytics.stg_attendance_attendee",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "individual_id": "individual_id",
            "register_id": "register_id",
            "enrollment_date": "enrollment_date",
            "deenrollment_date": "deenrollment_date",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "tenantid": "tenant_id",
            "tag": "tag",
        },
    },

    {
        "name": "eg_wms_attendance_log",
        "raw_table": "analytics.attendance_log_events_raw",
        "bronze_table": "analytics.stg_attendance_log",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "individual_id": "individual_id",
            "register_id": "register_id",
            "status": "status",
            "time": "time",
            "event_type": "event_type",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "tenantid": "tenant_id",
            "clientreferenceid": "client_reference_id",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
        },
    },

    {
        "name": "eg_expense_bill",
        "raw_table": "analytics.expense_bill_events_raw",
        "bronze_table": "analytics.stg_expense_bill",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "billdate": "bill_date",
            "duedate": "due_date",
            "totalamount": "total_amount",
            "totalpaidamount": "total_paid_amount",
            "businessservice": "business_service",
            "referenceid": "reference_id",
            "fromperiod": "from_period",
            "toperiod": "to_period",
            "status": "status",
            "paymentstatus": "payment_status",
            "billnumber": "bill_number",
            "localitycode": "locality_code",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "eg_expense_billdetail",
        "raw_table": "analytics.expense_billdetail_events_raw",
        "bronze_table": "analytics.stg_expense_billdetail",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "referenceid": "reference_id",
            "billid": "bill_id",
            "totalamount": "total_amount",
            "totalpaidamount": "total_paid_amount",
            "paymentstatus": "payment_status",
            "status": "status",
            "fromperiod": "from_period",
            "toperiod": "to_period",
            "netlineitemamount": "net_line_item_amount",
            "totalattendance": "total_attendance",
            "workerid": "worker_id",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "eg_expense_lineitem",
        "raw_table": "analytics.expense_lineitem_events_raw",
        "bronze_table": "analytics.stg_expense_lineitem",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "billdetailid": "bill_detail_id",
            "tenantid": "tenant_id",
            "headcode": "head_code",
            "amount": "amount",
            "paidamount": "paid_amount",
            "type": "type",
            "status": "status",
            "paymentstatus": "payment_status",
            "islineitempayable": "is_line_item_payable",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "eg_expense_party",
        "raw_table": "analytics.expense_party_events_raw",
        "bronze_table": "analytics.stg_expense_party",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "type": "type",
            "status": "status",
            "identifier": "identifier",
            "parentid": "parent_id",
            "paymentprovider": "payment_provider",
            "payeename": "payee_name",
            "payeephonenumber": "payee_phone_number",
            "bankaccount": "bank_account",
            "bankcode": "bank_code",
            "beneficiarycode": "beneficiary_code",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "household_member",
        "raw_table": "analytics.household_member_events_raw",
        "bronze_table": "analytics.stg_household_member",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "individualid": "individual_id",
            "individualclientreferenceid": "individual_client_reference_id",
            "householdid": "household_id",
            "householdclientreferenceid": "household_client_reference_id",
            "isheadofhousehold": "is_head_of_household",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "individual_address",
        "raw_table": "analytics.individual_address_events_raw",
        "bronze_table": "analytics.stg_individual_address",
        "page_size": 10000,
        "columns": {
            "individualid": "individual_id",
            "addressid": "address_id",
            "type": "type",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "isdeleted": "is_deleted",
        },
    },

    {
        "name": "referral",
        "raw_table": "analytics.referral_events_raw",
        "bronze_table": "analytics.stg_referral",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "projectbeneficiaryid": "project_beneficiary_id",
            "projectbeneficiaryclientreferenceid": "project_beneficiary_client_reference_id",
            "referrerid": "referrer_id",
            "recipientid": "recipient_id",
            "recipienttype": "recipient_type",
            "reasons": "reasons",
            "sideeffectid": "side_effect_id",
            "sideeffectclientreferenceid": "side_effect_client_reference_id",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedby": "client_last_modified_by",
            "clientlastmodifiedtime": "client_last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
            "additionaldetails": "additional_details",
            "referralcode": "referral_code",
            "projectid": "project_id",
        },
    },

    {
        "name": "side_effect",
        "raw_table": "analytics.side_effect_events_raw",
        "bronze_table": "analytics.stg_side_effect",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "taskid": "task_id",
            "taskclientreferenceid": "task_client_reference_id",
            "projectbeneficiaryid": "project_beneficiary_id",
            "projectbeneficiaryclientreferenceid": "project_beneficiary_client_reference_id",
            "symptoms": "symptoms",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedby": "client_last_modified_by",
            "clientlastmodifiedtime": "client_last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
            "additionaldetails": "additional_details",
        },
    },

    {
        "name": "hf_referral",
        "raw_table": "analytics.hf_referral_events_raw",
        "bronze_table": "analytics.stg_hf_referral",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "projectfacilityid": "project_facility_id",
            "symptom": "symptom",
            "symptomsurveyid": "symptom_survey_id",
            "beneficiaryid": "beneficiary_id",
            "referralcode": "referral_code",
            "nationallevelid": "national_level_id",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedby": "client_last_modified_by",
            "clientlastmodifiedtime": "client_last_modified_time",
            "rowversion": "row_version",
            "isdeleted": "is_deleted",
            "additionaldetails": "additional_details",
            "localitycode": "locality_code",
        },
    },

    {
        "name": "user_action",
        "raw_table": "analytics.user_action_events_raw",
        "bronze_table": "analytics.stg_user_action",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "clientreferenceid": "client_reference_id",
            "tenantid": "tenant_id",
            "projectid": "project_id",
            "latitude": "latitude",
            "longitude": "longitude",
            "locationaccuracy": "location_accuracy",
            "boundarycode": "boundary_code",
            "action": "action",
            "beneficiarytag": "beneficiary_tag",
            "resourcetag": "resource_tag",
            "status": "status",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "createdtime": "created_time",
            "lastmodifiedby": "last_modified_by",
            "lastmodifiedtime": "last_modified_time",
            "clientcreatedtime": "client_created_time",
            "clientlastmodifiedtime": "client_last_modified_time",
            "clientcreatedby": "client_created_by",
            "clientlastmodifiedby": "client_last_modified_by",
            "rowversion": "row_version",
        },
    },

    {
        "name": "eg_wms_muster_roll",
        "raw_table": "analytics.muster_roll_events_raw",
        "bronze_table": "analytics.stg_muster_roll",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenant_id": "tenant_id",
            "musterroll_number": "musterroll_number",
            "attendance_register_id": "attendance_register_id",
            "start_date": "start_date",
            "end_date": "end_date",
            "musterroll_status": "musterroll_status",
            "status": "status",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "reference_id": "reference_id",
            "service_code": "service_code",
            "billing_period_id": "billing_period_id",
        },
    },

    {
        "name": "eg_wms_attendance_summary",
        "raw_table": "analytics.attendance_summary_events_raw",
        "bronze_table": "analytics.stg_attendance_summary",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "individual_id": "individual_id",
            "muster_roll_id": "muster_roll_id",
            "musterroll_number": "musterroll_number",
            "actual_total_attendance": "actual_total_attendance",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "modified_total_attendance": "modified_total_attendance",
            "billing_period_id": "billing_period_id",
            "total_registrations": "total_registrations",
            "total_interventions": "total_interventions",
            "tag": "tag",
            "role": "role",
        },
    },

    {
        "name": "eg_service",
        "raw_table": "analytics.service_events_raw",
        "bronze_table": "analytics.stg_service",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "servicedefid": "service_def_id",
            "referenceid": "reference_id",
            "accountid": "account_id",
            "clientid": "client_id",
            "additionaldetails": "additional_details",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
        },
    },

    {
        "name": "eg_service_attribute_value",
        "raw_table": "analytics.service_attribute_value_events_raw",
        "bronze_table": "analytics.stg_service_attribute_value",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "referenceid": "reference_id",
            "attributecode": "attribute_code",
            "value": "value",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
            "serviceclientreferenceid": "service_client_reference_id",
        },
    },

    {
        "name": "eg_service_definition",
        "raw_table": "analytics.service_definition_events_raw",
        "bronze_table": "analytics.stg_service_definition",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "tenantid": "tenant_id",
            "code": "code",
            "isactive": "is_active",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "additionaldetails": "additional_details",
            "clientid": "client_id",
        },
    },

    {
        "name": "eg_push_device_tokens",
        "raw_table": "analytics.device_tokens_events_raw",
        "bronze_table": "analytics.stg_device_tokens",
        "page_size": 10000,
        "columns": {
            "id": "id",
            "userid": "user_id",
            "devicetype": "device_type",
            "tenantid": "tenant_id",
            "createdby": "created_by",
            "lastmodifiedby": "last_modified_by",
            "createdtime": "created_time",
            "lastmodifiedtime": "last_modified_time",
            "facilityid": "facility_id",
            "userroles": "user_roles",
        },
    },
]
