ALTER TABLE PROJECT_TASK ADD COLUMN IF NOT EXISTS clientCreatedTime bigint;
ALTER TABLE PROJECT_TASK ADD COLUMN IF NOT EXISTS clientLastModifiedTime bigint;

ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN IF NOT EXISTS clientCreatedTime bigint;
ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN IF NOT EXISTS clientLastModifiedTime bigint;

