ALTER TABLE PROJECT_TASK ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_TASK ADD COLUMN clientLastModifiedTime bigint;

ALTER TABLE PROJECT_STAFF ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_STAFF ADD COLUMN clientLastModifiedTime bigint;

ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN clientLastModifiedTime bigint;

ALTER TABLE PROJECT_RESOURCE ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_RESOURCE ADD COLUMN clientLastModifiedTime bigint;

ALTER TABLE PROJECT_FACILITY ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_FACILITY ADD COLUMN clientLastModifiedTime bigint;
