CREATE INDEX idx_id ON PROJECT_STAFF (id);
CREATE INDEX idx_tenantId ON PROJECT_STAFF (tenantId);
CREATE INDEX idx_staffId ON PROJECT_STAFF (staffId);
CREATE INDEX idx_projectId ON PROJECT_STAFF (projectId);
CREATE INDEX idx_startDate ON PROJECT_STAFF (startDate);
CREATE INDEX idx_endDate ON PROJECT_STAFF (endDate);
