ALTER TABLE PROJECT_TASK ADD COLUMN IF NOT EXISTS clientCreatedBy character varying(64);
ALTER TABLE PROJECT_TASK ADD COLUMN IF NOT EXISTS clientLastModifiedBy character varying(64);

ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN IF NOT EXISTS clientCreatedBy character varying(64);
ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN IF NOT EXISTS clientLastModifiedBy character varying(64);
