ALTER TABLE PROJECT_TASK ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_TASK ADD COLUMN clientLastModifiedTime bigint;

ALTER TABLE PROJECT_STAFF DROP COLUMN IF EXISTS clientCreatedTime bigint;
ALTER TABLE PROJECT_STAFF DROP COLUMN IF EXISTS clientLastModifiedTime bigint;

ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN clientCreatedTime bigint;
ALTER TABLE PROJECT_BENEFICIARY ADD COLUMN clientLastModifiedTime bigint;

ALTER TABLE PROJECT_RESOURCE DROP COLUMN IF EXISTS clientCreatedTime bigint;
ALTER TABLE PROJECT_RESOURCE DROP COLUMN IF EXISTS clientLastModifiedTime bigint;

ALTER TABLE PROJECT_FACILITY DROP COLUMN IF EXISTS clientCreatedTime bigint;
ALTER TABLE PROJECT_FACILITY DROP COLUMN IF EXISTS clientLastModifiedTime bigint;
