openapi: 3.0.3
info:
  title: Boundary Bulk Service API
  description: |
    Boundary Bulk Service provides APIs for bulk boundary operations including:
    - Bulk boundary creation with Excel file upload
    - Process tracking and status monitoring
    - Template generation for boundary uploads
    - Template search functionality
    
    All operations support asynchronous processing with process ID tracking.
  version: 1.0.0


paths:
  /boundary-bulk-service/boundary/_create:
    post:
      summary: Create boundaries in bulk
      description: |
        Creates boundaries in bulk from an uploaded Excel file. This is an asynchronous operation 
        that returns a process ID for tracking. The actual boundary creation happens in the background.
      tags:
        - Boundary Operations
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - RequestInfo
                - BoundaryDetails
                - file
              properties:
                RequestInfo:
                  $ref: '#/components/schemas/RequestInfo'
                BoundaryDetails:
                  $ref: '#/components/schemas/BoundaryCreateDetails'
                file:
                  type: string
                  format: binary
                  description: Excel file containing boundary data
      responses:
        '202':
          description: Request accepted for processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: '#/components/schemas/ResponseInfo'
                  ProcessDetails:
                    $ref: '#/components/schemas/ProcessDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /boundary-bulk-service/boundary/_search:
    post:
      summary: Search boundary creation processes
      description: |
        Search for boundary creation processes by various criteria including 
        process ID, tenant ID, hierarchy type, and status.
      tags:
        - Boundary Operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - RequestInfo
                - SearchCriteria
              properties:
                RequestInfo:
                  $ref: '#/components/schemas/RequestInfo'
                SearchCriteria:
                  $ref: '#/components/schemas/BoundarySearchCriteria'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: '#/components/schemas/ResponseInfo'
                  BoundaryProcessDetails:
                    type: array
                    items:
                      $ref: '#/components/schemas/BoundaryProcessDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /boundary-bulk-service/boundary/template/_generate:
    post:
      summary: Generate boundary template
      description: |
        Generates an Excel template for boundary upload. Can optionally include 
        existing boundary data. Results are cached for performance.
      tags:
        - Template Operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - RequestInfo
                - TemplateGenerateDetails
              properties:
                RequestInfo:
                  $ref: '#/components/schemas/RequestInfo'
                TemplateGenerateDetails:
                  $ref: '#/components/schemas/TemplateGenerateDetails'
      responses:
        '200':
          description: Template generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: '#/components/schemas/ResponseInfo'
                  TemplateDetails:
                    $ref: '#/components/schemas/TemplateDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /boundary-bulk-service/boundary/template/_search:
    post:
      summary: Search boundary templates
      description: |
        Search for previously generated boundary templates by tenant ID and hierarchy type.
      tags:
        - Template Operations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - RequestInfo
                - SearchCriteria
              properties:
                RequestInfo:
                  $ref: '#/components/schemas/RequestInfo'
                SearchCriteria:
                  $ref: '#/components/schemas/TemplateSearchCriteria'
      responses:
        '200':
          description: Template search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseInfo:
                    $ref: '#/components/schemas/ResponseInfo'
                  Templates:
                    type: array
                    items:
                      $ref: '#/components/schemas/TemplateRecord'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    RequestInfo:
      type: object
      required:
        - authToken
        - userInfo
      properties:
        authToken:
          type: string
          description: Authentication token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        userInfo:
          $ref: '#/components/schemas/UserInfo'
        msgId:
          type: string
          description: Unique message identifier
          example: "1234567890"
        ts:
          type: integer
          format: int64
          description: Timestamp
          example: 1634567890000

    UserInfo:
      type: object
      required:
        - uuid
        - tenantId
      properties:
        uuid:
          type: string
          description: User unique identifier
          example: "user-123-456-789"
        tenantId:
          type: string
          description: Tenant ID
          example: "pb.amritsar"
        userName:
          type: string
          description: Username
          example: "john.doe"
        name:
          type: string
          description: User full name
          example: "John Doe"
        roles:
          type: array
          items:
            type: string
          description: User roles
          example: ["SYSTEM_ADMINISTRATOR", "BOUNDARY_ADMIN"]

    ResponseInfo:
      type: object
      properties:
        apiId:
          type: string
          description: API identifier
        ver:
          type: string
          description: API version
        ts:
          type: integer
          format: int64
          description: Response timestamp
        resMsgId:
          type: string
          description: Response message ID
        msgId:
          type: string
          description: Request message ID
        status:
          type: string
          enum: [SUCCESSFUL, FAILED]
          description: Response status

    BoundaryCreateDetails:
      type: object
      required:
        - tenantId
        - hierarchyType
        - fileType
      properties:
        tenantId:
          type: string
          description: Tenant identifier
          example: "pb.amritsar"
        hierarchyType:
          type: string
          description: Boundary hierarchy type
          example: "ADMIN"
        fileType:
          type: string
          enum: [excel]
          description: Type of uploaded file
          example: "excel"

    ProcessDetails:
      type: object
      properties:
        processId:
          type: string
          format: uuid
          description: Unique process identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: string
          enum: [started, completed, failed]
          description: Process status
          example: "started"

    BoundarySearchCriteria:
      type: object
      required:
        - tenantId
      properties:
        processId:
          type: string
          format: uuid
          description: Process ID to search for
          example: "123e4567-e89b-12d3-a456-426614174000"
        tenantId:
          type: string
          description: Tenant identifier
          example: "pb.amritsar"
        hierarchyType:
          type: string
          description: Boundary hierarchy type
          example: "ADMIN"
        status:
          type: string
          enum: [started, completed, failed]
          description: Process status to filter by
          example: "completed"

    BoundaryProcessDetails:
      type: object
      properties:
        processId:
          type: string
          format: uuid
          description: Process identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        status:
          type: string
          enum: [started, completed, failed]
          description: Process status
          example: "completed"
        fileStoreId:
          type: string
          description: Original file store ID
          example: "file-123-456"
        processedFileStoreId:
          type: string
          description: Processed file store ID
          example: "file-123-456-processed"
        tenantId:
          type: string
          description: Tenant identifier
          example: "pb.amritsar"
        hierarchyType:
          type: string
          description: Boundary hierarchy type
          example: "ADMIN"
        createdBy:
          type: string
          description: User who created the process
          example: "user-123-456-789"
        createdTime:
          type: integer
          format: int64
          description: Process creation time
          example: 1634567890000
        lastModifiedBy:
          type: string
          description: User who last modified the process
          example: "user-123-456-789"
        lastModifiedTime:
          type: integer
          format: int64
          description: Last modification time
          example: 1634567890000
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ProcessError'
          description: List of errors if any
        fileUrl:
          type: string
          description: URL to download original file
          example: "https://filestore.egovernments.org/file-123-456"
        processedFileUrl:
          type: string
          description: URL to download processed file
          example: "https://filestore.egovernments.org/file-123-456-processed"

    ProcessError:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Error message
          example: "Invalid hierarchy data in row 5"
        rowNumber:
          type: integer
          description: Row number where error occurred
          example: 5

    TemplateGenerateDetails:
      type: object
      required:
        - tenantId
        - hierarchyType
      properties:
        tenantId:
          type: string
          description: Tenant identifier
          example: "pb.amritsar"
        hierarchyType:
          type: string
          description: Boundary hierarchy type
          example: "ADMIN"
        campaignId:
          type: string
          description: Campaign identifier (optional)
          example: "campaign-123"
        includeExistingBoundaries:
          type: boolean
          description: Whether to include existing boundary data in template
          default: false
          example: true

    TemplateDetails:
      type: object
      properties:
        fileStoreId:
          type: string
          description: File store ID of generated template
          example: "template-123-456"
        templateUrl:
          type: string
          description: URL to download the template
          example: "https://filestore.egovernments.org/template-123-456"

    TemplateSearchCriteria:
      type: object
      required:
        - tenantId
      properties:
        tenantId:
          type: string
          description: Tenant identifier
          example: "pb.amritsar"
        hierarchyType:
          type: string
          description: Boundary hierarchy type
          example: "ADMIN"

    TemplateRecord:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Template record identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        tenantId:
          type: string
          description: Tenant identifier
          example: "pb.amritsar"
        hierarchyType:
          type: string
          description: Boundary hierarchy type
          example: "ADMIN"
        campaignId:
          type: string
          description: Campaign identifier
          example: "campaign-123"
        fileStoreId:
          type: string
          description: File store ID
          example: "template-123-456"
        createdBy:
          type: string
          description: User who created the template
          example: "user-123-456-789"
        createdTime:
          type: integer
          format: int64
          description: Template creation time
          example: 1634567890000
        templateUrl:
          type: string
          description: URL to download the template
          example: "https://filestore.egovernments.org/template-123-456"

    ErrorResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: '#/components/schemas/ResponseInfo'
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Error message
          example: "Required field is missing"
        description:
          type: string
          description: Detailed error description
          example: "The field 'tenantId' is required but was not provided"


tags:
  - name: Boundary Operations
    description: Operations related to bulk boundary creation and management
  - name: Template Operations
    description: Operations related to boundary template generation and search