CREATE TABLE ADDRESS
(
    id                character varying(64),
    tenantId          character varying(1000),
    doorNo            character varying(64),
    latitude          float,
    longitude         float,
    locationAccuracy  int,
    type              character varying(64),
    addressLine1      character varying(256),
    addressLine2      character varying(256),
    landmark          character varying(256),
    city              character varying(256),
    pincode           character varying(64),
    buildingName      character varying(256),
    street            character varying(256),
    additionalDetails jsonb,
    localityCode      character varying(64),
    createdBy         character varying(64),
    createdTime       bigint,
    lastModifiedBy    character varying(64),
    lastModifiedTime  bigint,
    rowVersion        bigint,
    isDeleted         boolean,
    CONSTRAINT uk_address_id PRIMARY KEY (id)
);