# ----- Kafka Configuration --------------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.retries=5
spring.kafka.producer.acks=all
# Custom Topics
kafka.dlq.topic=fhir.dlq
kafka.failed.topic=fhir.resource.failed

# ----- Application Configuration ----------------------------
app.tenant-id=dev


# ----------------- Facility APIs ----------------------------
facility.search.url=https://unified-dev.digit.org/facility/v1/_search
facility.create.url=https://unified-dev.digit.org/facility/v1/bulk/_create
facility.update.url=https://unified-dev.digit.org/facility/v1/bulk/_update


# ----------------- Product Variant APIs ----------------------------
product.variant.search.url=https://unified-dev.digit.org/product/variant/v1/_search
product.variant.create.url=https://unified-dev.digit.org/product/variant/v1/_create
product.variant.update.url=https://unified-dev.digit.org/product/variant/v1/_update

# ----------------- Stock APIs ----------------------------
stock.search.url=https://unified-dev.digit.org/stock/v1/_search
stock.create.url=https://unified-dev.digit.org/stock/v1/bulk/_create
stock.update.url=https://unified-dev.digit.org/stock/v1/bulk/_update


# ----------------- Stock Reconciliation APIs --------------
stock.reconciliation.search.url=https://unified-dev.digit.org/stock/reconciliation/v1/_search
stock.recon.create.url=https://unified-dev.digit.org/stock/reconciliation/v1/bulk/_create
stock.recon.update.url=https://unified-dev.digit.org/stock/reconciliation/v1/bulk/_update


# ----------------- Boundary APIs --------------------------
boundary.relationship.search.url=https://unified-dev.digit.org/boundary-service/boundary-relationships/_search
boundary.create.url=https://unified-dev.digit.org/boundary-service/boundary-relationships/_create
boundary.update.url=https://unified-dev.digit.org/boundary-service/boundary-relationships/_update
