@startuml
title Project - UserAction - Bulk Create
!theme vibrant
participant Client as c
participant ProjectService as s
participant RedisCache as rc
participant IDGenService as idgen
queue Kafka as k
participant PersisterService as prs
participant IndexerService as idx
participant ErrorService as es
participant ElasticSearch as el
database Database as db
participant HandleErrorMethod as he
c -> s : /user-action/v1/bulk/_create
activate s
s -> s: Validate request body
activate s
s -> s: Validate request body
alt request validation fails
    s -> s: Request validation failed
    s -> c: HttpStatus: 400 with appropriate error code
    note left
        Error Code: REQUEST_VALIDATION_FAILED
    end note
end
s -> s: Request validation successful
s -> c: HttpStatus: 202 ACCEPTED
loop for each userAction
    alt record already exists
        alt record found in cache
          s -> rc: Check using clientReferenceId/serverGeneratedId
          activate rc
          rc -> s: 1 row
          deactivate rc
          s -> he: call handleError HandleErrorMethod
          note left
              Error Code: RECORD_ALREADY_EXISTS
          end note
        end
        s -> rc: Check using clientReferenceId/serverGeneratedId
        activate rc
        rc -> s: 0 rows
        deactivate rc
        s -> db: Check if record already exists
        activate db
        db -> s: 1 row
        deactivate db
        s -> rc: Put data in cache using clientReferenceId/serverGeneratedId
        activate rc
        deactivate rc
        s -> he: call handleError HandleErrorMethod
        note left
            Error Code: RECORD_ALREADY_EXISTS
        end note
    end
    alt projectId invalid
    s -> db: Check if projectId exists
    activate db
    db -> s: 0 rows
    deactivate db
    s -> he: call handleError HandleErrorMethod
        note left
            This will be marked as unrecoverable right away
            and require manual intervention
            Error Code: BAD_REQUEST
        end note
end
s -> db: Check if projectId exists
activate db
db -> s: 1 row
deactivate db
alt projectBeneficiaryId invalid
    s -> db: Check if projectBeneficiaryId exists
    activate db
    db -> s: 0 rows
    deactivate db
    s -> he: call handleError HandleErrorMethod
    note left
        This will be marked as recoverable and will be
        retried later
        Error Code: DEPENDENCY_ERROR
    end note
end
s -> db: Check if projectBeneficiaryId exists
activate db
db -> s: 1 row
deactivate db
alt id generation fails
    s -> idgen: /id/_generate
    activate idgen
    idgen -> s: HttpStatus: 400
    deactivate idgen
    s -> he: call handleError HandleErrorMethod
    note left
        This will be marked as recoverable and
        will be retried later
        Error Code: ID_GENERATION_FAILED
    end note
end
s -> idgen: Generate ID
activate idgen
idgen -> s: Generated ID
deactivate idgen
s -> s: Update generated ID in UserAction Data
s -> k: UserAction Data /persist_topic
activate k
s -> rc: Put UserAction Data against clientReferenceId/serverGeneratedId in cache
activate rc
deactivate rc
deactivate s
group async
    prs -> k: Consume UserAction Data
    activate prs
    idx -> k: Consume UserAction Data
    activate idx
    idx -> el: Store UserAction Data
    activate el
    deactivate el
    deactivate idx
    prs -> db: Persist UserAction Data
    activate db
    deactivate db
    deactivate prs
end
deactivate k
end
@enduml
