@startuml
title Project - User Action - Update
!theme vibrant
participant Client as c
participant ProjectService as s
participant RedisCache as rc
queue Kafka as k
participant PersisterService as prs
participant IndexerService as idx
participant ErrorService as es
participant ElasticSearch as el
database Database as db
c -> s : /project/user-action/v1/_update
activate s
s -> s: Validate request body
alt request validation fails
     s -> s: Request validation failed
     s -> c: HttpStatus: 400 with appropriate error code
    note left
      Error Code: REQUEST_VALIDATION_FAILED
    end note
end
s -> s: Request validation successful
alt record doesn't exist
    s -> rc: Search record based on clientReferenceId/serverGeneratedId
    activate rc
    rc -> s: 0 rows
    deactivate rc
    s -> db: Search record based on clientReferenceId/serverGeneratedId
    activate db
    db -> s: 0 row
    deactivate db
    s -> c: HttpStatus: 400 with appropriate error code
    note left
      Error Code: RECORD_NOT_FOUND
    end note
end
alt record doesn't exists in cache
    s -> rc: Search record based on clientReferenceId/serverGeneratedId
    activate rc
    rc -> s: 0 rows
    deactivate rc
    s -> db: Search record based on clientReferenceId/serverGeneratedId
    activate db
    db -> s: 1 row
    deactivate db
    s -> rc: 1 record
    activate rc
    deactivate rc
end
s -> rc: Fetch the existing record
activate rc
rc -> s: 1 row
deactivate rc
alt incorrect rowVersion
    s -> s: Compare rowVersion between request and db
    s -> s: Incorrect rowVersion [request: should be +1 only]
    s -> c: HttpStatus: 400 with appropriate error code
    note left
      Error Code: BAD_REQUEST
    end note
end
s -> s: Compare rowVersion between request and db
s -> s: rowVersion in request = rowVersion in db + 1
s -> k: Project User Action Data /update_topic
activate k
s -> rc: Update new record in cache against clientReferenceId/serverGeneratedId
activate rc
deactivate rc
s -> c: HttpStatus: 202 ACCEPTED
deactivate s
group async
    prs -> k: Consume Project User Action Data
    activate prs
    idx -> k: Consume Project User Action Data
    activate idx
    idx -> el: Store Project User Action Data
    activate el
    deactivate el
    deactivate idx
    prs -> db: Update Project User Action Data
    activate db
    deactivate db
    deactivate prs
end
deactivate k
@enduml