CREATE INDEX IF NOT EXISTS idx_id ON INDIVIDUAL (id);
CREATE INDEX IF NOT EXISTS idx_clientReferenceId ON INDIVIDUAL (clientReferenceId);
CREATE INDEX IF NOT EXISTS idx_givenName ON INDIVIDUAL (givenName);
CREATE INDEX IF NOT EXISTS idx_familyName ON INDIVIDUAL (familyName);
CREATE INDEX IF NOT EXISTS idx_otherNames ON INDIVIDUAL (otherNames);
CREATE INDEX IF NOT EXISTS idx_dateOfBirth ON INDIVIDUAL (dateOfBirth);
CREATE INDEX IF NOT EXISTS idx_gender ON INDIVIDUAL (gender);

CREATE INDEX IF NOT EXISTS idx_localityCode ON ADDRESS (localityCode);

CREATE INDEX IF NOT EXISTS idx_id ON INDIVIDUAL_IDENTIFIER (id);
CREATE INDEX IF NOT EXISTS idx_individualId ON INDIVIDUAL_IDENTIFIER (individualId);
CREATE INDEX IF NOT EXISTS idx_identifierType ON INDIVIDUAL_IDENTIFIER (identifierType);
CREATE INDEX IF NOT EXISTS idx_identifierId ON INDIVIDUAL_IDENTIFIER (identifierId);
CREATE INDEX IF NOT EXISTS idx_isDeleted ON INDIVIDUAL_IDENTIFIER (isDeleted);
CREATE INDEX IF NOT EXISTS idx_createdBy ON INDIVIDUAL_IDENTIFIER (createdBy);
CREATE INDEX IF NOT EXISTS idx_lastModifiedBy ON INDIVIDUAL_IDENTIFIER (lastModifiedBy);
CREATE INDEX IF NOT EXISTS idx_createdTime ON INDIVIDUAL_IDENTIFIER (createdTime);
CREATE INDEX IF NOT EXISTS idx_lastModifiedTime ON INDIVIDUAL_IDENTIFIER (lastModifiedTime);