"""dst_common - shared orchestration helpers for the DST DAGs.

Also puts the DST pipeline on sys.path. In this repo the DAGs and the pipeline
live in different trees, and Airflow only adds its own dags folder:

    utilities/airflow-dags/dags/      <- on sys.path (Airflow)
    utilities/campaign-data-analysis-report/         <- pipeline lives here

Without this, every DAG fails at import with "No module named 'pipeline'".
Resolution order:
  1. pipeline already importable  -> do nothing (dev layout, or PYTHONPATH set)
  2. $DST_PIPELINE_PATH           -> explicit override
  3. ../../../campaign-data-analysis-report      -> the repo layout, derived from this file

GENERATED by sync_to_fork.py in the DST automation working copy.
"""
import os
import sys


def _ensure_pipeline_importable():
    import importlib.util
    if importlib.util.find_spec("pipeline") is not None:
        return None

    candidates = []
    override = (os.getenv("DST_PIPELINE_PATH") or "").strip()
    if override:
        candidates.append(override)

    # .../utilities/airflow-dags/dags/dst_common/__init__.py
    #  -> up 3 = .../utilities  -> utilities/campaign-data-analysis-report
    here = os.path.dirname(os.path.abspath(__file__))
    utilities = os.path.dirname(os.path.dirname(os.path.dirname(here)))
    candidates.append(os.path.join(utilities, "campaign-data-analysis-report"))

    for path in candidates:
        if os.path.isdir(os.path.join(path, "pipeline")):
            if path not in sys.path:
                sys.path.insert(0, path)
            return path

    raise ImportError(
        "The DST pipeline package could not be located, so the DAGs cannot "
        "run. Looked in: " + ", ".join(repr(c) for c in candidates) + ". Fix by "
        "either setting DST_PIPELINE_PATH to the directory CONTAINING "
        "'pipeline', or putting utilities/campaign-data-analysis-report on the workers' "
        "PYTHONPATH.")


PIPELINE_ROOT = _ensure_pipeline_importable()
