package org.egov.transformer;

public interface Constants {
    String PROJECT_TYPES = "projectTypes";

    String MDMS_RESPONSE = "MdmsRes";

    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

    String PROJECT = "PROJECT";
    String WAREHOUSE = "WAREHOUSE";

    String HCM_DELIVERY_CONFIGURATION_MODULE ="HCM-DELIVERY-CONFIGURATION";
    String HCM_DELIVERY_CONFIGURATION_MASTER ="deliveryConfiguration";

    String HCM_FIELD_APP_CONFIGURATION_MODULE ="HCM-FIELD-APP-CONFIG";
    String HCM_FIELD_APP_CONFIGURATION_MASTER ="appConfig";
    String DELIVERY_COMMENT_OPTIONS_POPULATOR ="DELIVERY_COMMENT_OPTIONS_POPULATOR";
    String PROGRAM_MANDATE ="PROGRAM_MANDATE";

}
