CREATE TABLE REFERRAL
(
    id                   				character varying(64),
    clientReferenceId    				character varying(64),
    tenantId             				character varying(1000),
    projectBeneficiaryId     			character varying(64),
    projectBeneficiaryClientReferenceId character varying(64),
    referrerId             			    character varying(100),
    recipientId          				character varying(100),
    recipientType      				character varying(100),
    reasons    							jsonb,
    sideEffectId 						character varying(100),
    sideEffectClientReferenceId         character varying(100),
    createdBy            				character varying(64),
    createdTime          				bigint,
    lastModifiedBy       				character varying(64),
    lastModifiedTime     				bigint,
    clientCreatedBy                     character varying(64),
    clientCreatedTime                   bigint,
    clientLastModifiedBy       			character varying(64),
    clientLastModifiedTime     			bigint,
    rowVersion           				bigint,
    isDeleted            				boolean,
    CONSTRAINT uk_referral_id PRIMARY KEY (id),
    CONSTRAINT uk_referral_clientReferenceId UNIQUE (clientReferenceId)
);
