CREATE table IF NOT EXISTS hf_referral (
    id character varying(64),
    clientreferenceid character varying(64),
    tenantid character varying(1000),
    projectid character varying(64),
    facilityId character varying(64),
    symptom character varying(256),
    symptomsurveyid character varying(100),
    beneficiaryid character varying(100),
    referralcode character varying(100),
    nationallevelid character varying(100),
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    clientcreatedby character varying(64),
    clientcreatedtime bigint,
    clientlastmodifiedby character varying(64),
    clientlastmodifiedtime bigint,
    rowversion bigint,
    isdeleted boolean,
    additionaldetails jsonb,
    CONSTRAINT uk_hf_referral_id PRIMARY KEY (id),
    CONSTRAINT uk_hf_referral_clientReferenceId UNIQUE (clientReferenceId)
);