# Native image properties for household service
Args = --no-fallback \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=org.slf4j,ch.qos.logback \
       --trace-class-initialization=org.postgresql.Driver \
       -H:+ReportExceptionStackTraces \
       -Dspring.native.remove-yaml-support=false \
       -Dspring.spel.ignore=true