"""empty message

Revision ID: 1.0.2
Revises: 
Create Date: 2025-11-06 14:38:04.929252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1.0.2'
down_revision = '1.0.1'
branch_labels = None
depends_on = None

def upgrade():

    op.execute("""
        INSERT INTO macro (name, description) VALUES
        ('LAST_MONTH_START_TO_END', 'Last month start to end date.')
    """)

    op.execute("""
        UPDATE productinfo SET version = '1.0.2', updated_at = NOW()
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE productinfo SET version = '1.0.1', updated_at = NOW()
    """)
    # ### end Alembic commands ###
