"""empty message

Revision ID: 1.0.5
Revises: 
Create Date: 2025-11-14 14:38:04.929252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1.0.5'
down_revision = '1.0.4'
branch_labels = None
depends_on = None

def upgrade():

    op.execute('''
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'chatinfo'
                AND column_name = 'embedding'
            ) THEN
                ALTER TABLE chatinfo ADD COLUMN embedding DOUBLE PRECISION[];
            END IF;
        END $$;
    ''')

    op.execute("""
        UPDATE chatinfo SET is_correct = NULL, updated_at = NOW()
    """)

    op.execute("""
        UPDATE productinfo SET version = '1.0.5', updated_at = NOW()
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE productinfo SET version = '1.0.4', updated_at = NOW()
    """)
    # ### end Alembic commands ###
