"""empty message

Revision ID: 1.0.1
Revises: 
Create Date: 2025-10-01 14:38:04.929252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1.0.1'
down_revision = '1.0.0'
branch_labels = None
depends_on = None

def upgrade():

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('SimilaritySearchThresholdScore', 'Similarity search threshold score', 'The minimum similarity score (between 0 and 100) required for retrieved results to be considered relevant.', 'Float', '50', False, True, 'Admin', Now())"
    )

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('SimilaritySearchMaxCount', 'Similarity search maximum count', 'The maximum number of most similar results to retrieve from the similarity search.', 'Integer', '10', False, True, 'Admin', Now())"
    )

    op.execute("""
        UPDATE productinfo SET version = '1.0.1', updated_at = NOW()
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE productinfo SET version = '1.0.0', updated_at = NOW()
    """)
    # ### end Alembic commands ###
