"""empty message

Revision ID: 1.0.0
Revises: 
Create Date: 2024-06-23 14:38:04.929252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1.0.0'
down_revision = None
branch_labels = None
depends_on = None

ui_json = '''{
  "login_logo_url": "https://prescienceds.com/wp-content/uploads/2022/10/logo.png",
  "login_logo_background_color": "white",
  "login_button_color": "",
  "navbar_background_color": "",
  "navbar_logo_url": ""
}'''


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "insert into productinfo(product_name, company, version, created_at) \
            values ('AI Chatbot', 'Prescience Decision Solutions', '1.0.0', Now())"
    )
    
    op.execute(
        f"insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('UISettings', 'UI settings (JSON)', 'All UI settings as key and value in json.', 'Json', '{ui_json}', False, True, 'Admin', Now())"
    )
    
    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('ChatHistoryRetentionPeriod', 'Chat history retention period (in Days)', 'Setting for retaining chat history for given no of days.', 'Integer', '45', False, True, 'Admin', Now())"
    )

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('ChatHistoryCleanupJobSchedule', 'Chat history clean up job schedule (in Hours)', 'Setting for chat history cleanup job schedule.', 'Integer', '48', False, True, 'Admin', Now())"
    )

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('QueryDefaultRowCount', 'Default number of rows returned by the query output', 'Setting for returning default no of rows in the query output.', 'Integer', '5', False, True, 'Admin', Now())"
    )

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('QueryMaxRowCount', 'Maximum number of rows returned by the query output', 'Setting for returning maximum no of rows in the query output.', 'Integer', '20', False, True, 'Admin', Now())"
    )

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('HistoryMaxRowCount', 'Maximum rows included in the historical context', 'Setting for maximum no of rows for history contenxt.', 'Integer', '10', False, True, 'Admin', Now())"
    )

    op.execute("""
        INSERT INTO macro (name, description) VALUES
        ('CURRENT_YEAR', 'The current year.'),
        ('CURRENT_MONTH', 'The current month.'),
        ('CURRENT_DATE', 'The current full date.'),
        ('LAST_YEAR', 'The previous year relative to the current date.'),
        ('LAST_MONTH', 'The month before the current month.'),
        ('YESTERDAY_DATE', 'The date for the previous day.'),
        ('NEXT_YEAR', 'The year after the current year.'),
        ('NEXT_MONTH', 'The month after the current month.'),
        ('DB_TYPE', 'The database type being used.'),
        ('TABLE_NAME', 'The specific table name(s) being referenced or queried.'),
        ('TABLE_SCHEMA', 'The schema name under which the table is defined.'),
        ('TABLE_INFO', 'Structured metadata about the table(s), including column names, data types, and relationships.'),
        ('TOP_K', 'The number of rows to be retrieved in a query.'),
        ('MAX_ROWS', 'The maximum number of rows returned in query output.')
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print('In downgrade')
    # ### end Alembic commands ###
