"""empty message

Revision ID: 1.0.6
Revises: 
Create Date: 2025-11-17 14:38:04.929252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1.0.6'
down_revision = '1.0.5'
branch_labels = None
depends_on = None

def upgrade():

    op.execute(
        "insert into platformconfig(name, display_name, help_msg, type, value, readonly, is_active, created_by, created_at) \
            values ('UserFeedbackSimilaritySearchThresholdScore', 'User feedback similarity search threshold score', 'The minimum similarity score (between 0 and 100) required for retrieved results to be considered relevant.', 'Float', '80', False, True, 'Admin', Now())"
    )
    
    op.execute("""
        UPDATE productinfo SET version = '1.0.6', updated_at = NOW()
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE productinfo SET version = '1.0.5', updated_at = NOW()
    """)
    # ### end Alembic commands ###
