"""empty message

Revision ID: 1.0.7
Revises: 
Create Date: 2025-11-18 14:38:04.929252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1.0.7'
down_revision = '1.0.6'
branch_labels = None
depends_on = None

def upgrade():

    op.execute(
        "CREATE INDEX idx_chatinfo_config_correct ON chatinfo (config_id_fk, is_correct);"
    )
    
    op.execute("""
        UPDATE productinfo SET version = '1.0.7', updated_at = NOW()
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE productinfo SET version = '1.0.6', updated_at = NOW()
    """)
    # ### end Alembic commands ###
