serviceMaps:
  serviceName: household
  mappings:
    - version: 1.0
      description: Persists household.
      fromTopic: save-household-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: HOUSEHOLD
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      userUuidJsonPath: $.[0].auditDetails.createdBy
      transactionCodeJsonPath: $.clientReferenceId
      auditAttributeBasePath: $.*
      queryMaps:
        - query: INSERT INTO health.HOUSEHOLD(id, tenantId, clientReferenceId, householdType, numberOfMembers, addressId, additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted, clientCreatedTime, clientLastModifiedTime, clientCreatedBy, clientLastModifiedBy) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.id
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.clientReferenceId
            - jsonPath: $.*.householdType
            - jsonPath: $.*.memberCount
            - jsonPath: $.*.address.id
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.createdBy
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.createdTime
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.clientAuditDetails.createdTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.createdBy
            - jsonPath: $.*.clientAuditDetails.lastModifiedBy
        - query: INSERT INTO health.ADDRESS(id, clientReferenceId, tenantid, doorno, latitude, longitude, locationAccuracy, type, addressline1, addressline2, landmark, city, pincode, buildingName, street, localityCode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.*.address
          jsonMaps:
            - jsonPath: $.*.address.id
            - jsonPath: $.*.address.clientReferenceId
            - jsonPath: $.*.address.tenantId
            - jsonPath: $.*.address.doorNo
            - jsonPath: $.*.address.latitude
            - jsonPath: $.*.address.longitude
            - jsonPath: $.*.address.locationAccuracy
            - jsonPath: $.*.address.type
            - jsonPath: $.*.address.addressLine1
            - jsonPath: $.*.address.addressLine2
            - jsonPath: $.*.address.landmark
            - jsonPath: $.*.address.city
            - jsonPath: $.*.address.pincode
            - jsonPath: $.*.address.buildingName
            - jsonPath: $.*.address.street
            - jsonPath: $.*.address.locality.code

    - version: 1.0
      description: Updates household.
      fromTopic: update-household-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: HOUSEHOLD
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      userUuidJsonPath: $.[0].auditDetails.createdBy
      transactionCodeJsonPath: $.clientReferenceId
      auditAttributeBasePath: $.*
      queryMaps:
        - query: UPDATE health.HOUSEHOLD SET tenantId = ?, clientReferenceId = ?, numberOfMembers = ?, addressId = ?, additionalDetails = ?, lastModifiedBy = ?, lastModifiedTime = ?, rowVersion = ?, isDeleted = ?, clientLastModifiedTime = ?, clientLastModifiedBy = ? WHERE ID = ?;
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.clientReferenceId
            - jsonPath: $.*.memberCount
            - jsonPath: $.*.address.id
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedBy
            - jsonPath: $.*.id
        - query: INSERT INTO health.ADDRESS(id, clientReferenceId, tenantid, doorno, latitude, longitude, locationAccuracy, type, addressline1, addressline2, landmark, city, pincode, buildingName, street, localityCode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET tenantId = ?, doorno = ?, latitude = ?, longitude = ?, locationAccuracy = ?, type = ?, addressline1 = ?, addressline2 = ?, landmark = ?, city = ?, pincode = ?, buildingName = ?, street = ?, localityCode = ?;
          basePath: $.*.address
          jsonMaps:
            - jsonPath: $.*.address.id
            - jsonPath: $.*.address.clientReferenceId
            - jsonPath: $.*.address.tenantId
            - jsonPath: $.*.address.doorNo
            - jsonPath: $.*.address.latitude
            - jsonPath: $.*.address.longitude
            - jsonPath: $.*.address.locationAccuracy
            - jsonPath: $.*.address.type
            - jsonPath: $.*.address.addressLine1
            - jsonPath: $.*.address.addressLine2
            - jsonPath: $.*.address.landmark
            - jsonPath: $.*.address.city
            - jsonPath: $.*.address.pincode
            - jsonPath: $.*.address.buildingName
            - jsonPath: $.*.address.street
            - jsonPath: $.*.address.locality.code
            - jsonPath: $.*.address.tenantId
            - jsonPath: $.*.address.doorNo
            - jsonPath: $.*.address.latitude
            - jsonPath: $.*.address.longitude
            - jsonPath: $.*.address.locationAccuracy
            - jsonPath: $.*.address.type
            - jsonPath: $.*.address.addressLine1
            - jsonPath: $.*.address.addressLine2
            - jsonPath: $.*.address.landmark
            - jsonPath: $.*.address.city
            - jsonPath: $.*.address.pincode
            - jsonPath: $.*.address.buildingName
            - jsonPath: $.*.address.street
            - jsonPath: $.*.address.locality.code

    - version: 1.0
      description: Deletes household.
      fromTopic: delete-household-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: HOUSEHOLD
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      userUuidJsonPath: $.[0].auditDetails.createdBy
      transactionCodeJsonPath: $.clientReferenceId
      auditAttributeBasePath: $.*
      queryMaps:
        - query: UPDATE health.HOUSEHOLD SET lastModifiedBy = ?, lastModifiedTime = ?, clientLastModifiedTime = ?, clientLastModifiedBy = ?,  rowVersion = ?, isDeleted = ?, additionalDetails=? WHERE ID = ?;
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedBy
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.id

    - version: 1.0
      description: Persists household member.
      fromTopic: save-household-member-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: HOUSEHOLD
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      userUuidJsonPath: $.[0].auditDetails.createdBy
      transactionCodeJsonPath: $.clientReferenceId
      auditAttributeBasePath: $.*
      queryMaps:
        - query: INSERT INTO health.HOUSEHOLD_MEMBER(id, tenantId, clientReferenceId, individualId, individualClientReferenceId, householdId, householdClientReferenceId, isHeadOfHousehold, additionalDetails, createdBy, lastModifiedBy, createdTime, lastModifiedTime, rowVersion, isDeleted, clientCreatedTime, clientLastModifiedTime, clientCreatedBy, clientLastModifiedBy) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.id
            - jsonPath: $.*.tenantId
            - jsonPath: $.*.clientReferenceId
            - jsonPath: $.*.individualId
            - jsonPath: $.*.individualClientReferenceId
            - jsonPath: $.*.householdId
            - jsonPath: $.*.householdClientReferenceId
            - jsonPath: $.*.isHeadOfHousehold
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.createdBy
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.createdTime
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.clientAuditDetails.createdTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.createdBy
            - jsonPath: $.*.clientAuditDetails.lastModifiedBy
        - query: INSERT INTO health.HOUSEHOLD_MEMBER_RELATIONSHIP(id, clientReferenceId, tenantId, selfId, selfClientReferenceId, relativeId, relativeClientReferenceId, relationshipType, createdBy, lastModifiedBy, createdTime, lastModifiedTime, clientCreatedBy, clientLastModifiedBy, clientCreatedTime, clientLastModifiedTime, rowVersion, isDeleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.*.memberRelationships.*
          jsonMaps:
            - jsonPath: $.*.memberRelationships.*.id
            - jsonPath: $.*.memberRelationships.*.clientReferenceId
            - jsonPath: $.*.memberRelationships.*.tenantId
            - jsonPath: $.*.memberRelationships.*.selfId
            - jsonPath: $.*.memberRelationships.*.selfClientReferenceId
            - jsonPath: $.*.memberRelationships.*.relativeId
            - jsonPath: $.*.memberRelationships.*.relativeClientReferenceId
            - jsonPath: $.*.memberRelationships.*.relationshipType
            - jsonPath: $.*.memberRelationships.*.auditDetails.createdBy
            - jsonPath: $.*.memberRelationships.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.memberRelationships.*.auditDetails.createdTime
            - jsonPath: $.*.memberRelationships.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.memberRelationships.*.clientAuditDetails.createdBy
            - jsonPath: $.*.memberRelationships.*.clientAuditDetails.lastModifiedBy
            - jsonPath: $.*.memberRelationships.*.clientAuditDetails.createdTime
            - jsonPath: $.*.memberRelationships.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.memberRelationships.*.rowVersion
            - jsonPath: $.*.memberRelationships.*.isDeleted
    - version: 1.0
      description: Update household member.
      fromTopic: update-household-member-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: HOUSEHOLD
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      userUuidJsonPath: $.[0].auditDetails.createdBy
      transactionCodeJsonPath: $.clientReferenceId
      auditAttributeBasePath: $.*
      queryMaps:
        - query: UPDATE health.HOUSEHOLD_MEMBER SET isHeadOfHousehold=?, clientReferenceId = ?, additionalDetails=?, lastModifiedBy=?, lastModifiedTime=?, rowVersion=?, isDeleted=?, clientLastModifiedTime = ?, clientLastModifiedBy = ? WHERE individualId=? AND householdId=? AND isDeleted=false;
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.isHeadOfHousehold
            - jsonPath: $.*.clientReferenceId
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedBy
            - jsonPath: $.*.individualId
            - jsonPath: $.*.householdId
        - query: UPDATE health.HOUSEHOLD_MEMBER_RELATIONSHIP SET relationshipType=?, relativeId=?, relativeClientReferenceId=?, lastModifiedBy=?, lastModifiedTime=?, clientLastModifiedBy=?, clientLastModifiedTime=?, rowVersion=?, isDeleted=? WHERE selfId=? AND isDeleted=false;
          basePath: $.*.memberRelationships.*
          jsonMaps:
            - jsonPath: $.*.memberRelationships.*.relationshipType
            - jsonPath: $.*.memberRelationships.*.relativeId
            - jsonPath: $.*.memberRelationships.*.relativeClientReferenceId
            - jsonPath: $.*.memberRelationships.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.memberRelationships.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.memberRelationships.*.clientAuditDetails.lastModifiedBy
            - jsonPath: $.*.memberRelationships.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.memberRelationships.*.rowVersion
            - jsonPath: $.*.memberRelationships.*.isDeleted
            - jsonPath: $.*.memberRelationships.*.selfId
    - version: 1.0
      description: Deletes household Member.
      fromTopic: delete-household-member-health-topic
      isTransaction: true
      isAuditEnabled: true
      module: HOUSEHOLD
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      userUuidJsonPath: $.[0].auditDetails.createdBy
      transactionCodeJsonPath: $.clientReferenceId
      auditAttributeBasePath: $.*
      queryMaps:
        - query: UPDATE health.HOUSEHOLD_MEMBER SET lastModifiedBy = ?, lastModifiedTime = ?, clientLastModifiedTime = ?, clientLastModifiedBy = ?, rowVersion = ?, isDeleted = ?, additionalDetails=? WHERE ID = ?;
          basePath: $.*
          jsonMaps:
            - jsonPath: $.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedTime
            - jsonPath: $.*.clientAuditDetails.lastModifiedBy
            - jsonPath: $.*.rowVersion
            - jsonPath: $.*.isDeleted
            - jsonPath: $.*.additionalFields
              type: JSON
              dbType: JSONB
            - jsonPath: $.*.id
        - query: UPDATE health.HOUSEHOLD_MEMBER_RELATIONSHIP SET lastModifiedBy = ?, lastModifiedTime = ?, rowVersion = ?, isDeleted = ? WHERE selfId = ?;
          basePath: $.*.memberRelationships.*
          jsonMaps:
            - jsonPath: $.*.memberRelationships.*.auditDetails.lastModifiedBy
            - jsonPath: $.*.memberRelationships.*.auditDetails.lastModifiedTime
            - jsonPath: $.*.memberRelationships.*.rowVersion
            - jsonPath: $.*.memberRelationships.*.isDeleted
            - jsonPath: $.*.memberRelationships.*.selfId