serviceMaps:
  serviceName: API Resource Service
  mappings:
    - version: 1.0
      name: CreateResourceDetails
      description: Create resource details in the eg_cm_resource_details table
      fromTopic: create-resource-details
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_resource_details(id, "status", tenantId, fileStoreId,processedFileStoreId,"action", campaignId,"type", createdBy, createdTime, lastModifiedBy, lastModifiedTime, additionalDetails, hierarchytype) VALUES (?, ?,?, ?,?,?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.ResourceDetails
          jsonMaps:
            - jsonPath: $.ResourceDetails.id
            - jsonPath: $.ResourceDetails.status
            - jsonPath: $.ResourceDetails.tenantId
            - jsonPath: $.ResourceDetails.fileStoreId
            - jsonPath: $.ResourceDetails.processedFileStoreId
            - jsonPath: $.ResourceDetails.action
            - jsonPath: $.ResourceDetails.campaignId
            - jsonPath: $.ResourceDetails.type
            - jsonPath: $.ResourceDetails.auditDetails.createdBy
            - jsonPath: $.ResourceDetails.auditDetails.createdTime
            - jsonPath: $.ResourceDetails.auditDetails.lastModifiedBy
            - jsonPath: $.ResourceDetails.auditDetails.lastModifiedTime
            - jsonPath: $.ResourceDetails.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.ResourceDetails.hierarchyType



    - version: 1.0
      name: UpdateResourceDetails
      description: Update resource details in the eg_cm_resource_details table
      fromTopic: update-resource-details
      isTransaction: true
      queryMaps:
        - query: UPDATE health.eg_cm_resource_details SET "status" = ?, processedFileStoreId = ?, lastModifiedBy = ?, lastModifiedTime = ?,additionalDetails = ? WHERE id = ?;
          basePath: $.ResourceDetails
          jsonMaps:
            - jsonPath: $.ResourceDetails.status
            - jsonPath: $.ResourceDetails.processedFileStoreId
            - jsonPath: $.ResourceDetails.auditDetails.lastModifiedBy
            - jsonPath: $.ResourceDetails.auditDetails.lastModifiedTime
            - jsonPath: $.ResourceDetails.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.ResourceDetails.id


    - version: 1.0
      name: CreateResourceActivity
      description: Create resource activity in the eg_cm_resource_activity table
      fromTopic: create-resource-activity
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_resource_activity (id, "status", retryCount,tenantId, type, url, requestPayload, responsePayload, createdBy, createdTime, lastModifiedBy, lastModifiedTime, additionalDetails, resourceDetailsId) VALUES (?, ?,?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?,?);
          basePath: $.Activities.*
          jsonMaps:
            - jsonPath: $.Activities.*.id
            - jsonPath: $.Activities.*.status
            - jsonPath: $.Activities.*.retryCount
            - jsonPath: $.Activities.*.tenantId
            - jsonPath: $.Activities.*.type
            - jsonPath: $.Activities.*.url
            - jsonPath: $.Activities.*.requestPayload
              type: JSON
              dbType: JSONB
            - jsonPath: $.Activities.*.responsePayload
              type: JSON
              dbType: JSONB
            - jsonPath: $.Activities.*.auditDetails.createdBy
            - jsonPath: $.Activities.*.auditDetails.createdTime
            - jsonPath: $.Activities.*.auditDetails.lastModifiedBy
            - jsonPath: $.Activities.*.auditDetails.lastModifiedTime
            - jsonPath: $.Activities.*.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.Activities.*.resourceDetailsId


    - version: 1.0
      name: CreateForGenerateApiResources
      description: Create Api resource in the eg_cm_generated_resource_details table
      fromTopic: create-generated-resource-details
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_generated_resource_details (id,filestoreid, type,"status",count,tenantid,hierarchyType, createdby, createdtime, lastmodifiedby, lastmodifiedtime, additionaldetails,campaignid, locale) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?);
          basePath: generatedResource.*
          jsonMaps:
            - jsonPath: $.generatedResource.*.id
            - jsonPath: $.generatedResource.*.fileStoreid
            - jsonPath: $.generatedResource.*.type
            - jsonPath: $.generatedResource.*.status
            - jsonPath: $.generatedResource.*.count
            - jsonPath: $.generatedResource.*.tenantId
            - jsonPath: $.generatedResource.*.hierarchyType
            - jsonPath: $.generatedResource.*.auditDetails.createdBy
            - jsonPath: $.generatedResource.*.auditDetails.createdTime
            - jsonPath: $.generatedResource.*.auditDetails.lastModifiedBy
            - jsonPath: $.generatedResource.*.auditDetails.lastModifiedTime
            - jsonPath: $.generatedResource.*.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.generatedResource.*.campaignId
            - jsonPath: $.generatedResource.*.locale



    - version: 1.0
      name: UpdateForGenerateApiResources
      description: Update Api resource in the eg_cm_generated_resource_details table
      fromTopic: update-generated-resource-details
      isTransaction: true
      queryMaps:
        - query: UPDATE health.eg_cm_generated_resource_details SET status = ?,count=?, lastModifiedby =? , lastModifiedtime = ? , fileStoreid= ?, additionalDetails= ? WHERE id= ?;
          basePath: generatedResource.*
          jsonMaps:
            - jsonPath: $.generatedResource.*.status
            - jsonPath: $.generatedResource.*.count
            - jsonPath: $.generatedResource.*.auditDetails.lastModifiedBy
            - jsonPath: $.generatedResource.*.auditDetails.lastModifiedTime
            - jsonPath: $.generatedResource.*.fileStoreid
            - jsonPath: $.generatedResource.*.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.generatedResource.*.id


    - version: 1.0
      name: CreateCampaignDetails
      description: Create campaign details in the eg_cm_campaign_details table
      fromTopic: save-project-campaign-details
      isTransaction: true
      isAuditEnabled: true
      module: HCM
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.campaignNumber
      auditAttributeBasePath: $.CampaignDetails
      queryMaps:
        - query: INSERT INTO health.eg_cm_campaign_details(id, tenantId, "status","action",campaignName,projectType, campaignNumber,hierarchyType,boundaryCode, projectId,parentId,isActive,startDate,endDate, createdBy, createdTime, lastModifiedBy, lastModifiedTime, additionalDetails,campaignDetails) VALUES (?,?,?,?,?,?, ?,?, ?,?,?,?, ?, ?, ?, ?, ?, ?,?,?);
          basePath: $.CampaignDetails
          jsonMaps:
            - jsonPath: $.CampaignDetails.id
            - jsonPath: $.CampaignDetails.tenantId
            - jsonPath: $.CampaignDetails.status
            - jsonPath: $.CampaignDetails.action
            - jsonPath: $.CampaignDetails.campaignName
            - jsonPath: $.CampaignDetails.projectType
            - jsonPath: $.CampaignDetails.campaignNumber
            - jsonPath: $.CampaignDetails.hierarchyType
            - jsonPath: $.CampaignDetails.boundaryCode
            - jsonPath: $.CampaignDetails.projectId
            - jsonPath: $.CampaignDetails.parentId
            - jsonPath: $.CampaignDetails.isActive
            - jsonPath: $.CampaignDetails.startDate
            - jsonPath: $.CampaignDetails.endDate
            - jsonPath: $.CampaignDetails.auditDetails.createdBy
            - jsonPath: $.CampaignDetails.auditDetails.createdTime
            - jsonPath: $.CampaignDetails.auditDetails.lastModifiedBy
            - jsonPath: $.CampaignDetails.auditDetails.lastModifiedTime
            - jsonPath: $.CampaignDetails.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.CampaignDetails.campaignDetails
              type: JSON
              dbType: JSONB


    - version: 1.0
      name: UpdateCampaignDetails
      description: Update campaign details in the eg_cm_campaign_details table
      fromTopic: update-project-campaign-details
      isTransaction: true
      isAuditEnabled: true
      module: HCM
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.campaignNumber
      auditAttributeBasePath: $.CampaignDetails
      queryMaps:
        - query: UPDATE health.eg_cm_campaign_details SET campaignName = ?, "status" = ?, action = ?, projectType = ?, hierarchyType = ?, boundaryCode = ?, projectId = ?, parentId = ?, isActive = ?,startDate=?,endDate=?, lastModifiedBy = ?, lastModifiedTime = ?, additionalDetails = ?, campaignDetails = ? WHERE id = ?;
          basePath: $.CampaignDetails
          jsonMaps:
            - jsonPath: $.CampaignDetails.campaignName
            - jsonPath: $.CampaignDetails.status
            - jsonPath: $.CampaignDetails.action
            - jsonPath: $.CampaignDetails.projectType
            - jsonPath: $.CampaignDetails.hierarchyType
            - jsonPath: $.CampaignDetails.boundaryCode
            - jsonPath: $.CampaignDetails.projectId
            - jsonPath: $.CampaignDetails.parentId
            - jsonPath: $.CampaignDetails.isActive
            - jsonPath: $.CampaignDetails.startDate
            - jsonPath: $.CampaignDetails.endDate
            - jsonPath: $.CampaignDetails.auditDetails.lastModifiedBy
            - jsonPath: $.CampaignDetails.auditDetails.lastModifiedTime
            - jsonPath: $.CampaignDetails.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.CampaignDetails.campaignDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.CampaignDetails.id

    - version: 1.0
      name: CreateProcessTrack
      description: Create process track in the eg_cm_campaign_process table
      fromTopic: save-process-track
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_campaign_process(id, campaignId, "type","status",details,createdtime, lastmodifiedtime,additionaldetails) VALUES (?,?,?,?,?,?,?,?);
          basePath: processDetails.*
          jsonMaps:
            - jsonPath: $.processDetails.*.id
            - jsonPath: $.processDetails.*.campaignId
            - jsonPath: $.processDetails.*.type
            - jsonPath: $.processDetails.*.status
            - jsonPath: $.processDetails.*.details
              type: JSON
              dbType: JSONB
            - jsonPath: $.processDetails.*.createdTime
            - jsonPath: $.processDetails.*.lastModifiedTime
            - jsonPath: $.processDetails.*.additionalDetails
              type: JSON
              dbType: JSONB

    - version: 1.0  
      name: UpdateProcessTrack
      description: Update process track in the eg_cm_campaign_process table
      fromTopic: update-process-track
      isTransaction: true
      queryMaps:
        - query: UPDATE health.eg_cm_campaign_process SET campaignId = ?, "type" = ?, "status" = ?,details = ?,createdtime = ?,lastmodifiedtime = ?,additionaldetails = ? WHERE id = ?;
          basePath: $.processDetails
          jsonMaps:
            - jsonPath: $.processDetails.campaignId
            - jsonPath: $.processDetails.type
            - jsonPath: $.processDetails.status
            - jsonPath: $.processDetails.details
              type: JSON
              dbType: JSONB
            - jsonPath: $.processDetails.createdTime
            - jsonPath: $.processDetails.lastModifiedTime
            - jsonPath: $.processDetails.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.processDetails.id


    - version: 1.0
      name: CreateSheetData
      description: Create sheet data in the eg_cm_campaign_data table
      fromTopic: save-sheet-data
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_campaign_data(campaignnumber, "type",uniqueidentifier,data,uniqueidafterprocess, "status") VALUES (?,?,?,?,?,?);
          basePath: datas.*
          jsonMaps:
            - jsonPath: $.datas.*.campaignNumber
            - jsonPath: $.datas.*.type
            - jsonPath: $.datas.*.uniqueIdentifier
            - jsonPath: $.datas.*.data
              type: JSON
              dbType: JSONB
            - jsonPath: $.datas.*.uniqueIdAfterProcess
            - jsonPath: $.datas.*.status


    - version: 1.0
      name: UpdateSheetData
      description: Update sheet data in the eg_cm_campaign_data table
      fromTopic: update-sheet-data
      isTransaction: true
      queryMaps:
        - query: UPDATE health.eg_cm_campaign_data SET data = ?,uniqueidafterprocess = ?, "status" = ? WHERE uniqueidentifier = ? AND "type" = ? AND campaignnumber = ?;
          basePath: datas.*
          jsonMaps:
            - jsonPath: $.datas.*.data
              type: JSON
              dbType: JSONB
            - jsonPath: $.datas.*.uniqueIdAfterProcess
            - jsonPath: $.datas.*.status
            - jsonPath: $.datas.*.uniqueIdentifier
            - jsonPath: $.datas.*.type
            - jsonPath: $.datas.*.campaignNumber

    - version: 1.0
      name: CreateMappingData
      description: Create mapping data in the eg_cm_campaign_mapping_data table
      fromTopic: save-mapping-data
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_campaign_mapping_data(campaignnumber,"type",uniqueIdentifierForData,boundaryCode,mappingId,"status") VALUES (?,?,?,?,?,?);
          basePath: datas.*
          jsonMaps:
            - jsonPath: $.datas.*.campaignNumber
            - jsonPath: $.datas.*.type
            - jsonPath: $.datas.*.uniqueIdentifierForData
            - jsonPath: $.datas.*.boundaryCode
            - jsonPath: $.datas.*.mappingId
            - jsonPath: $.datas.*.status


    - version: 1.0
      name: UpdateMappingData
      description: Update mapping data in the eg_cm_campaign_mapping_data table
      fromTopic: update-mapping-data
      isTransaction: true
      queryMaps:
        - query: UPDATE health.eg_cm_campaign_mapping_data SET mappingId = ?, "status" = ? WHERE uniqueIdentifierForData = ? AND campaignnumber = ? AND "type" = ? AND boundaryCode = ?;
          basePath: datas.*
          jsonMaps:
            - jsonPath: $.datas.*.mappingId
            - jsonPath: $.datas.*.status
            - jsonPath: $.datas.*.uniqueIdentifierForData
            - jsonPath: $.datas.*.campaignNumber
            - jsonPath: $.datas.*.type
            - jsonPath: $.datas.*.boundaryCode

    - version: 1.0
      name: DeleteMappingData
      description: Delete mapping data in the eg_cm_campaign_mapping_data table
      fromTopic: delete-mapping-data
      isTransaction: true
      queryMaps:
        - query: DELETE FROM health.eg_cm_campaign_mapping_data WHERE uniqueIdentifierForData = ? AND campaignnumber = ? AND "type" = ? AND boundaryCode = ?;
          basePath: datas.*
          jsonMaps:
            - jsonPath: $.datas.*.uniqueIdentifierForData
            - jsonPath: $.datas.*.campaignNumber
            - jsonPath: $.datas.*.type
            - jsonPath: $.datas.*.boundaryCode


    - version: 1.0
      name: CreateProcessData
      description: Create process data in the eg_cm_campaign_process_data table
      fromTopic: save-process-data
      isTransaction: true
      queryMaps:
        - query: INSERT INTO health.eg_cm_campaign_process_data(campaignnumber,processName, "status", createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?,?,?,?,?,?,?);
          basePath: processes.*
          jsonMaps:
            - jsonPath: $.processes.*.campaignNumber
            - jsonPath: $.processes.*.processName
            - jsonPath: $.processes.*.status
            - jsonPath: $.processes.*.auditDetails.createdBy
            - jsonPath: $.processes.*.auditDetails.lastModifiedBy
            - jsonPath: $.processes.*.auditDetails.createdTime
            - jsonPath: $.processes.*.auditDetails.lastModifiedTime

    - version: 1.0
      name: UpdateProcessData
      description: Update process data in the eg_cm_campaign_process_data table
      fromTopic: update-process-data
      isTransaction: true
      queryMaps:
        - query: UPDATE health.eg_cm_campaign_process_data SET "status" = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE campaignnumber = ? AND processName = ?;
          basePath: processes.*
          jsonMaps:
            - jsonPath: $.processes.*.status
            - jsonPath: $.processes.*.auditDetails.lastModifiedBy
            - jsonPath: $.processes.*.auditDetails.lastModifiedTime
            - jsonPath: $.processes.*.campaignNumber
            - jsonPath: $.processes.*.processName
