Args = --no-fallback \
       --enable-url-protocols=http,https \
       --enable-all-security-services \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -Djava.awt.headless=true \
       --initialize-at-run-time=org.apache.kafka \
       --initialize-at-run-time=org.postgresql.Driver \
       --initialize-at-run-time=org.postgresql.util.SharedTimer \
       --initialize-at-run-time=org.postgresql.PGProperty \
       --initialize-at-run-time=org.flywaydb.core \
       --initialize-at-run-time=org.egov.tracer.kafka
