name: Build Pipeline

on:
  push:
    branches:
      - ingestion-poc

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          VERSION="4.30.8"
          URL="https://github.com/mikefarah/yq/releases/download/v${VERSION}/yq_linux_amd64"
          sudo curl -sSL "$URL" -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Pick Dockerfile
        id: pick_dockerfile
        run: |
          SERVICE="excel-ingestion"
          DEFAULT_DOCKERFILE="build/maven/Dockerfile"

          # Excel ingestion special case
          if [ "$SERVICE" = "excel-ingestion" ]; then
            DF="build/maven-java17/Dockerfile"
          else
            DF="$DEFAULT_DOCKERFILE"
          fi

          echo "dockerfile_path=$DF" >> "$GITHUB_OUTPUT"
          echo "DOCKERFILE_PATH=$DF" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-excel-ingestion-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Generate the Next Tag
        id: tag
        run: |
          set -euxo pipefail
          BRANCH="${GITHUB_REF##*/}"
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SERVICE_NAME="excel-ingestion"
          NEXT_TAG="${BRANCH}-${COMMIT_HASH}"

          echo "tag=$NEXT_TAG" >> "$GITHUB_OUTPUT"
          echo "NEXT_TAG=$NEXT_TAG" >> "$GITHUB_ENV"

      - name: Build and Push Application Docker Image
        id: build_push_docker
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            egovio/excel-ingestion:${{ steps.tag.outputs.tag }}
          build-args: |
            WORK_DIR=health-services/excel-ingestion

      - name: Save Application Docker Image
        id: save_docker_image
        run: |
          IMG="egovio/excel-ingestion:${{ steps.tag.outputs.tag }}"
          echo "$IMG"
          echo "docker_image=$IMG" >> "$GITHUB_OUTPUT"
          echo "### Application Docker Image" >> "$GITHUB_STEP_SUMMARY"
          echo "$IMG" >> "$GITHUB_STEP_SUMMARY"
