name: Node.js Publish UI Packages

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'micro-ui/web/micro-ui-internals/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: cd micro-ui/web/micro-ui-internals/ && bash ./publish.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
